/* Command Center (mockup 01) and Missions (mockup 04) */
(() => {
  const { UI, C, I } = VQ, D = VQ.ops, H = D.home, IMG = f => `assets/img/${f}`;
  const alertRow = a => ({ thumb: a.img, title: a.title, titleTone: a.sev === 'critical' ? 'crit' : 'warn', sub: a.where, sub2: `${a.at} · Confidence ${a.conf}% · ${a.src}`, pill: UI.pill(a.sev[0].toUpperCase() + a.sev.slice(1), D.sevTone[a.sev]), go: 'alerts' });

  VQ.screen('cc', { ws: 'ops', title: 'Command Center', sub: 'Every drone, mission and alert across all sites, right now.', headRight: () => `<span class="row t2"><i class="dot" style="background:var(--good)"></i>Live · updated 08:42:17 AM</span>${UI.btn('Plan a Mission', { primary: 1, icon: 'plus', go: 'plan/area' })}`,
    views: { main: { render: () => { const uc = VQ.state.site || 'dam';
      return UI.kpis([{ icon: 'drone', bg: 'bg-navy', value: H.dronesActive, label: 'Drones Active', delta: { dot: 'good', text: `${H.inAir} in air · ${H.onGround} on ground` }, go: 'fleet' }, { icon: 'video', bg: 'bg-info', value: H.cameras, label: 'Cameras Online', delta: { dot: 'good', text: `${H.camOnline} online · 2 offline` }, go: 'payloads' },
        { icon: 'route', bg: 'bg-violet', value: H.activeMissions, label: 'Active Missions', delta: { text: `${D.missionStats.scheduled} scheduled today` }, go: 'missions' }, { icon: 'mappin', bg: 'bg-good', value: H.zones, label: 'Sites Monitored', delta: { dot: 'good', text: 'All airspace clear' }, go: 'airspace' },
        { icon: 'alert', bg: 'bg-crit', value: H.alerts, label: 'Active Alerts', delta: { text: '1 critical · 1 high · 1 medium' }, go: 'alerts' }, { icon: 'shieldcheck', bg: 'bg-good', value: H.success + '%', label: 'Mission Success Rate', delta: { dir: 'up', value: '+12%', text: 'vs. last month', good: true }, go: 'analytics' }], 'g6')
      + `<div class="grid g-2-1"><div class="card"><div class="card-h"><h3>Live Operations Map</h3><div class="right">${UI.seg('site', [['dam', 'North Ridge Dam'], ['highway', 'NH-44 Corridor'], ['refinery', 'Refinery (10:00 AM)']], uc)}<a data-go="live">Open Live Operations ${I('chev')}</a></div></div>${VQ.MMap.render({ uc, h: 400, layers: { area: 1, path: 1, nfz: 1, drones: 1 }, showLayers: [['drones', 'Drones (live)'], ['path', 'Flight path'], ['area', 'Mission area'], ['nfz', 'Geo-fence'], ['comms', 'Link coverage']] })}</div>
        ${UI.card(`Active Alerts (${D.alerts.length})`, UI.list(D.alerts.map(alertRow)) + '<div class="card-note mt">Each alert carries its clip, position and the mission that raised it.</div>', { right: UI.viewAll('alerts') })}</div>
      <div class="grid g3">${UI.card('Mission Overview', UI.table([{ k: 'id', label: 'Mission', fmt: (v, m) => `<b class="ink">${v.replace('M-2026-', 'M-')}</b> ${m.name}` }, { k: 'status', label: 'Status', fmt: v => UI.pill(v, D.statusTone[v]) }, { k: 'n', label: 'Drones', r: 1 }, { k: 'pct', label: 'Progress', fmt: v => `<div style="min-width:70px">${C.meter(v, v === 100 ? 'good' : '')}</div>` }], D.missions.slice(0, 5).map(m => ({ ...m, go: 'missions' }))), { right: UI.viewAll('missions') })}
        ${UI.card('Drone Fleet', `<div class="grid g3" style="margin:0 0 10px">${D.fleet.types.slice(0, 3).map(t => `<div style="text-align:center;border:1px solid var(--line);border-radius:8px;padding:8px"><div style="width:26px;height:26px;margin:0 auto;color:var(--navy-600)">${I('drone')}</div><div class="kpi-val" style="font-size:18px">${t[1]}</div><div class="kpi-lbl">${t[0]}</div></div>`).join('')}</div><div class="b ink small">Battery levels, drones on missions</div>${C.bars({ h: 120, labels: ['> 80%', '60–80%', '40–60%', '20–40%', '< 20%'], valueLabels: 1, series: [{ name: 'Drones', data: [10, 5, 2, 1, 0] }], unit: 'drones' })}`, { right: UI.viewAll('fleet') })}
        ${UI.card('Live Camera Feeds', `<div class="grid g2" style="margin:0;gap:8px">${[['feed-tankfarm.jpg', 'Camera 12 · Tank Farm'], ['feed-highway.jpg', 'DR-002 · NH-44 Km 81'], ['feed-perimeter.jpg', 'Camera 21 · Perimeter'], ['th-zoom.jpg', 'DR-003 · Dam spillway']].map(f => UI.cam({ img: f[0], label: f[1], go: 'live' })).join('')}</div>`, { right: UI.viewAll('live') })}</div>
      <div class="grid g-2-1">${UI.card('Mission Planning Workflow', `<div class="tl">${[['Plan', 'Define objective, area and payload', 'plan/area'], ['Orchestrate', 'Assign drones, set rules and airspace', 'plan/swarm'], ['Fly', 'Auto-execute or manual control', 'live'], ['Monitor', 'Live feeds and telemetry', 'live'], ['Analyze', 'AI insights and alerts', 'analytics'], ['Act', 'Respond and close the mission', 'alerts']].map((s, i) => `<div class="st done" data-go="${s[2]}" style="cursor:pointer"><i></i><b>${i + 1}. ${s[0]}</b><span>${s[1]}</span></div>`).join('')}</div>`)}
        ${UI.card('Quick Actions', UI.quick([{ icon: 'plus', label: 'Create Mission', go: 'plan/area' }, { icon: 'drone', label: 'Deploy Drone' }, { icon: 'net', label: 'Launch Swarm', go: 'swarm' }, { icon: 'video', label: 'View Live Feed', go: 'live' }, { icon: 'ban', label: 'No-Fly Zone', go: 'airspace' }, { icon: 'file', label: 'Download Report', go: 'reports' }]))}</div>`; } } } });

  /* ---------- Missions ---------- */
  VQ.screen('missions', { ws: 'ops', title: 'Missions', sub: 'Plan, track and manage all drone missions. From routine operations to complex swarm missions.', headRight: () => UI.btn('New Mission', { primary: 1, icon: 'plus', go: 'plan/area' }),
    views: { main: { render: () => { const S = D.missionStats, sel = D.missions.find(m => m.id === (VQ.state.m || 'M-2026-001')), tab = VQ.state.mt || 'overview', f = VQ.state.mf || 'all', rows = D.missions.filter(m => f === 'all' || m.status === f);
      const body = { overview: () => `<div class="card flush" style="box-shadow:none">${VQ.MMap.render({ uc: sel.uc || 'dam', h: 200, labels: false, layers: { area: 1, path: 1, nfz: 1, drones: sel.status === 'In Progress' } })}</div><div class="row between mt"><b class="ink">Mission Progress</b><span class="t2 small">${sel.status === 'In Progress' ? 'Est. completion 09:15 AM' : sel.status}</span></div><div class="row"><div class="kpi-val">${sel.pct}%</div><div class="grow">${C.meter(sel.pct, sel.pct === 100 ? 'good' : '')}</div></div>${UI.statRow([[sel.n, 'Drones'], ['120 m', 'Max altitude'], ['2.4 km²', 'Area'], ['48 min', 'Elapsed']])}`,
        live: () => `<div class="grid g3" style="margin:0;gap:8px">${['th-eo.jpg', 'th-thermal.jpg', 'th-zoom.jpg'].map(f => UI.cam({ img: sel.uc === 'dam' ? f : sel.img, live: sel.status === 'In Progress', cls: 'tall' })).join('')}</div><div class="row mt">${UI.btn('Open Live Operations', { sm: 1, primary: 1, go: 'live' })}</div>`,
        drones: () => UI.list(sel.drones.replace(/ \(.*\)/, '').split(', ').map(d => ({ icon: 'drone', tone: 'info', title: d, sub: sel.status === 'In Progress' ? 'In the air · link strong' : sel.status, go: 'fleet' }))),
        data: () => UI.kv([['video', 'Images captured', VQ.fmt(Math.round(8400 * sel.pct / 100))], ['db', 'Data', `${Math.round(320 * sel.pct / 100)} GB`], ['sparkles', 'AI detections', sel.alerts ? `${sel.alerts} alert, 6 tagged frames` : 'None'], ['grid', 'Coverage', `${Math.round(96 * sel.pct / 100)}%`]]),
        report: () => `<div class="card-note mb">${sel.pct === 100 ? 'The mission report is ready.' : 'The report is generated when the mission closes. A draft is available now.'}</div>${UI.btn(sel.pct === 100 ? 'Download Report' : 'Open Draft Report', { sm: 1, go: 'reports' })}` }[tab]();
      return UI.kpis([{ icon: 'file', bg: 'bg-navy', value: S.today, label: 'Missions Today', delta: { dir: 'up', value: '+27%', text: 'vs. last month', good: true } }, { icon: 'play', bg: 'bg-good', value: S.inProgress, label: 'In Progress' }, { icon: 'clock', bg: 'bg-info', value: S.scheduled, label: 'Scheduled' }, { icon: 'checkc', bg: 'bg-good', value: S.completedMonth, label: 'Completed (month)', delta: { dir: 'up', value: '+18%', text: 'vs. last month', good: true } }, { icon: 'alert', bg: 'bg-crit', value: S.withAlerts, label: 'With Alerts' }, { icon: 'clock', bg: 'bg-violet', value: S.flightHours, unit: 'hrs', label: 'Flight Time (week)' }], 'g6')
      + `<div class="grid g-2-1">${UI.card('All missions', UI.seg('mf', [['all', 'All'], ['In Progress', 'In Progress'], ['Scheduled', 'Scheduled'], ['Completed', 'Completed']], f) + `<div class="tbl-wrap mt"><table class="tbl"><thead><tr><th>Mission ID</th><th>Mission Name</th><th>Use Case</th><th>Location</th><th>Drones</th><th>Start</th><th>Status</th><th>Progress</th><th>Alerts</th></tr></thead><tbody>${rows.map(m => `<tr class="click" data-set="m=${m.id}" style="${m.id === sel.id ? 'background:var(--blue-50)' : ''}"><td><b style="color:var(--blue)">${m.id}</b></td><td><b class="ink">${m.name}</b></td><td>${m.use}</td><td>${m.loc}</td><td>${m.drones}</td><td>${m.start}</td><td>${UI.pill(m.status, D.statusTone[m.status])}</td><td><div style="min-width:64px">${C.meter(m.pct, m.status === 'Failed' ? 'crit' : m.pct === 100 ? 'good' : '')}</div></td><td>${m.alerts ? UI.pill(m.alerts, 'crit', 'alert') : '–'}</td></tr>`).join('')}</tbody></table></div><div class="card-note mt">Showing ${rows.length} of ${S.today} missions today. Select a row to see it on the right.</div>`)}
        <div class="card"><div class="row between"><div><div class="kpi-val">${sel.id}</div><div class="b ink">${sel.name}</div><div class="small t2">${sel.use} | ${sel.loc}</div></div>${UI.pill(sel.status, D.statusTone[sel.status])}</div><div class="mt mb">${UI.seg('mt', [['overview', 'Overview'], ['live', 'Live View'], ['drones', 'Drones'], ['data', 'Data'], ['report', 'Report']], tab)}</div>${body}
          <hr class="sep"><div class="b ink small mb">Recent Events</div>${UI.vtimeline([{ t: '08:22', text: 'Waypoint 4 completed', tone: 'good' }, { t: '08:18', text: sel.alerts ? 'Thermal anomaly detected' : 'Sector handover complete', tone: sel.alerts ? 'crit' : '' }, { t: '08:10', text: 'Battery at 60% on the lead drone' }, { t: '08:05', text: 'Entered the mission area', tone: 'good' }])}
          ${sel.uc ? `<div class="row mt">${UI.btn('Open this plan in Mission Planning', { sm: 1, toast: '' , go: 'plan/area' })}</div>` : ''}</div></div>`; } } } });
})();
