/* Take Control · pilot view for one drone: flight HUD, cameras, flight modes, ARM/DISARM, emergency override deck.
   Controls are gated by role. Role and drone are kept in storage so they survive navigation. */
(() => {
  const { UI, I } = VQ, D = VQ.ops;
  const ROLES = [['Super Admin', 'Complete system, flight command and mission authority.'], ['Fleet Manager', 'Fleet, mission planning and emergency overrides.'], ['Flight Operator', 'Routine flight: arm, disarm, modes and mission execution.'], ['Viewer / Auditor', 'Read-only telemetry, map and camera.']];
  const CAN = { arm: ['Super Admin', 'Flight Operator'], fly: ['Super Admin', 'Fleet Manager', 'Flight Operator'], emergency: ['Super Admin', 'Fleet Manager'] };
  const MODES = [['Stabilize', 'Manual flight, self-levelling'], ['Alt Hold', 'Holds altitude when the throttle is centred'], ['Pos Hold', 'Holds position and altitude when the sticks are released'], ['Guided', 'Point-and-click flight on the map'], ['Auto', 'Flies the uploaded mission'], ['RTL', 'Returns to the launch point'], ['Land', 'Descends and lands where it is'], ['Brake', 'Stops and holds station']];
  const OVR = { rtl: ['Override RTL', 'Return-to-Launch', 'home', 'Return-to-Launch started. The drone leaves its mission and flies the safe corridor home.'], land: ['Emergency Land', 'Immediate', 'down', 'Emergency land executed. The drone is descending at its current position.'], abort: ['Abort Mission', 'Hold position', 'x', 'Mission aborted. The aircraft is holding position.'], disarm: ['Force Disarm', 'Motors off', 'zap', 'Motors force-disarmed.'], kill: ['Kill Motors', 'Last resort', 'octagon', 'Motors killed. The aircraft will fall. Logged for review.'] };
  D.role = () => VQ.store.get('role', 'Flight Operator'); const can = a => CAN[a].includes(D.role());
  window.VQctl = { role: r => { VQ.store.set('role', r); VQ.render(true); }, mode: m => { if (!can('fly')) return VQ.toast('Flight mode change inhibited: your role is read-only.'); VQ.store.set('fmode', m); VQ.toast(`Flight mode: ${m}`); VQ.render(true); },
    arm: () => { if (!can('arm')) return VQ.toast('ARM/DISARM inhibited: needs Flight Operator or Super Admin.'); VQ.toast('Disarm refused while airborne. Land first, or use the emergency deck.'); },
    ask: k => { if (!can('emergency')) return VQ.toast('Emergency deck inhibited: needs Fleet Manager or Super Admin.'); VQ.set('ov', k); }, confirm: k => { VQ.store.set('fmode', k === 'rtl' ? 'RTL' : k === 'land' ? 'Land' : 'Brake'); VQ.state.ov = ''; VQ.state.last = k; VQ.toast('EMERGENCY OVERRIDE: ' + OVR[k][3]); VQ.render(true); } };

  const hud = (roll, pitch, hdg) => `<svg viewBox="0 0 200 120" style="width:100%;height:150px;background:#0a1630;border-radius:8px"><defs><clipPath id="ai"><circle cx="60" cy="60" r="46"/></clipPath></defs>
    <g clip-path="url(#ai)"><g transform="rotate(${roll} 60 60) translate(0 ${pitch * 2})"><rect x="-40" y="-60" width="200" height="120" fill="#2f7fd6"/><rect x="-40" y="60" width="200" height="120" fill="#8a5a2b"/><line x1="-40" y1="60" x2="160" y2="60" stroke="#fff" stroke-width="1.5"/>${[-20, -10, 10, 20].map(p => `<line x1="${p % 20 ? 50 : 44}" x2="${p % 20 ? 70 : 76}" y1="${60 - p * 2}" y2="${60 - p * 2}" stroke="#fff" stroke-width="1"/>`).join('')}</g></g>
    <circle cx="60" cy="60" r="46" fill="none" stroke="#8ea3c7" stroke-width="2"/><path d="M38,60 H52 L60,66 L68,60 H82" fill="none" stroke="#ffd21f" stroke-width="2.5"/><path d="M60,10 l-4,-7 h8z" fill="#ffd21f"/>
    <circle cx="150" cy="60" r="40" fill="#0e2248" stroke="#8ea3c7" stroke-width="2"/>${['N', 'E', 'S', 'W'].map((c, i) => { const a = (i * 90 - hdg - 90) * Math.PI / 180; return `<text x="${150 + Math.cos(a) * 30}" y="${64 + Math.sin(a) * 30}" text-anchor="middle" style="font:700 10px Inter;fill:${c === 'N' ? '#ff6a61' : '#cfe0ff'}">${c}</text>`; }).join('')}<path d="M150,32 l6,34 h-12z" fill="#ffd21f"/><text x="150" y="112" text-anchor="middle" style="font:600 9px Inter;fill:#cfe0ff">HDG ${String(hdg).padStart(3, '0')}°</text><text x="60" y="116" text-anchor="middle" style="font:600 9px Inter;fill:#cfe0ff">ROLL ${roll}° · PITCH ${pitch}°</text></svg>`;
  const stick = (lab, dx, dy) => `<div style="text-align:center"><svg viewBox="0 0 100 100" style="width:96px;height:96px"><circle cx="50" cy="50" r="44" fill="var(--blue-50)" stroke="var(--axis)" stroke-width="2"/><path d="M50,10 V90 M10,50 H90" stroke="var(--axis)"/><circle cx="${50 + dx}" cy="${50 + dy}" r="15" fill="var(--blue)" stroke="#fff" stroke-width="3"/></svg><div class="small t2">${lab}</div></div>`;

  VQ.screen('control', { ws: 'ops', rail: 'live', dark: true, title: 'Take Control', crumbs: [['Live Operations', 'live'], ['Take Control']], sub: 'Pilot view for one drone. What you can touch depends on your role.',
    views: { main: { render: () => { const c = VQ.store.get('ctl', { uc: 'dam', k: 0 }), U = D.usecases[c.uc] || D.usecases.dam, d = U.drones[c.k] || U.drones[0], role = D.role(), mode = VQ.store.get('fmode', 'Auto'), cv = VQ.state.cv || 'main', ov = VQ.state.ov, ro = !can('fly');
      const img = { dam: ['th-eo.jpg', 'th-zoom.jpg'], highway: ['feed-highway.jpg', 'hw-cam-corridor-1.jpg'], refinery: ['ref-feed-unit3.jpg', 'ref-cam-column.jpg'] }[U.key];
      return `${ro ? `<div class="banner warn mb">${I('lock')}<div><div class="k">Auditor mode</div><div class="v" style="font-size:15px">Flight command controls are inhibited for your role</div></div><div class="d">You can watch telemetry, map and camera. Switch role on the right to see the controls unlock.</div></div>` : ''}
      <div class="card mb" style="display:flex;gap:16px;align-items:center;flex-wrap:wrap"><div><div class="kpi-val">${d.id}</div><div class="small t2">${d.name} · ${d.model} · ${U.name}</div></div>${UI.pill('CONNECTED', 'solid-good')}${UI.pill('GPS 3D Fix (14 sats)', 'good')}<span class="batt"><i style="--p:${d.batt - 30}%;--c:var(--good)"></i>${d.batt - 30}%</span>
        <button class="btn ${can('arm') ? '' : 'ghost'}" onclick="VQctl.arm()" data-tip="${can('arm') ? 'Vehicle is armed. Click to disarm.' : 'ARM/DISARM inhibited for your role'}">${I(can('arm') ? 'zap' : 'lock')}ARMED${can('arm') ? '' : ' (LOCKED)'}</button><span class="grow"></span>
        <div><div class="small t2">Signed in as</div><div class="seg">${ROLES.map(r => `<button class="${r[0] === role ? 'on' : ''}" onclick="VQctl.role('${r[0]}')" data-tip="${r[1]}">${r[0]}</button>`).join('')}</div></div></div>
      <div class="grid g-2-1"><div class="col">
        ${UI.card('Camera', UI.cam({ img: img[cv === 'main' ? 0 : 1], cls: cv === 'thermal' ? 'thermal' : '', label: `${d.id} · ${cv === 'fpv' ? 'FPV Cam' : cv === 'thermal' ? 'Thermal' : 'Main Cam'}`, time: '08:42:17 AM', foot: d.sector, extra: `<div class="hud">ALT ${U.alt} m · GS ${U.speed} m/s · VSI +0.2 m/s<br>MODE ${mode.toUpperCase()} · ${U.lat.toFixed(4)} N, ${U.lon.toFixed(4)} E</div>` })
          + `<div class="row wrap mt">${UI.btn('Capture Photo', { sm: 1, icon: 'video', toast: 'Drone photo captured' })}${UI.btn('Start Recording', { sm: 1, icon: 'clip', toast: 'Recording live stream in 4K', done: 'Recording' })}${UI.btn('Screenshot', { sm: 1, icon: 'expand', toast: 'Screen capture saved' })}<span class="grow"></span><span class="small t2">Gimbal</span>${['up', 'down'].map(x => `<button class="btn sm ghost" style="min-width:0" data-act="${ro ? 'Gimbal control inhibited for your role' : 'Gimbal pitch ' + (x === 'up' ? '+5°' : '−5°')}">${I(x)}</button>`).join('')}<button class="btn sm ghost" data-act="${ro ? 'Gimbal control inhibited for your role' : 'Gimbal centred'}">Centre</button></div>`, { right: UI.seg('cv', [['main', 'Main Cam'], ['fpv', 'FPV Cam'], ['thermal', 'Thermal']], cv) })}
        ${UI.card('Flight mode', `<div class="opt-grid" style="grid-template-columns:repeat(4,minmax(0,1fr))">${MODES.map(m => `<button class="opt ${m[0] === mode ? 'on' : ''}" onclick="VQctl.mode('${m[0]}')" data-tip="${m[1]}" style="${ro ? 'opacity:.55' : ''}"><b>${m[0]}</b><span style="font-size:10.5px">${m[1]}</span></button>`).join('')}</div>`, { right: `<span class="small">Now: <b class="ink">${mode}</b></span>` })}</div>
      <div class="col">
        ${UI.card('Flight HUD', hud(-4, 2, 72) + UI.statRow([[`${U.alt} m`, 'Altitude AGL'], [`${U.speed} m/s`, 'Ground speed'], ['+0.2 m/s', 'Climb']]), { icon: 'gauge' })}
        <div class="card" style="border:1.5px solid var(--crit)"><div class="card-h">${I('alert')}<h3 style="color:var(--crit-ink)">Emergency Override Deck</h3><div class="right">${can('emergency') ? UI.pill('Unlocked', 'good') : UI.pill('Fleet Manager or Super Admin', 'gray', 'lock')}</div></div>
          ${ov ? `<div class="chk bad">${I('octagon')}<div><b>Confirm: ${OVR[ov][0]}</b><span>${OVR[ov][3]} This is logged with your name and role.</span></div></div><div class="row mt"><button class="btn primary" style="background:var(--crit);border-color:var(--crit)" onclick="VQctl.confirm('${ov}')">Confirm Override</button><button class="btn ghost" data-set="ov=">Cancel</button></div>`
            : `<div class="grid g2" style="margin:0;gap:8px">${Object.entries(OVR).map(([k, o]) => `<button class="btn" style="height:46px;justify-content:flex-start;border-color:var(--crit);color:var(--crit-ink);${can('emergency') ? '' : 'opacity:.5'}${k === 'kill' ? ';grid-column:1/-1;background:var(--crit-bg)' : ''}" onclick="VQctl.ask('${k}')">${I(o[2])}<span style="text-align:left;line-height:1.15">${o[0]}<br><small style="font-weight:500">${o[1]}</small></span></button>`).join('')}</div>${VQ.state.last ? `<div class="card-note mt">Last override: <b class="ink">${OVR[VQ.state.last][0]}</b>, 08:42 AM, by ${D.user} (${role}).</div>` : '<div class="card-note mt">Every override asks for confirmation and is written to the audit log.</div>'}`}</div>
        ${UI.card('Manual sticks', `<div class="row" style="justify-content:space-around;${ro ? 'opacity:.45' : ''}">${stick('Throttle / Yaw', 0, mode === 'Auto' ? 0 : -8)}${stick('Pitch / Roll', mode === 'Auto' ? 0 : 6, 0)}</div><div class="card-note mt">${mode === 'Auto' ? 'Sticks are idle while the mission flies itself. Pick Pos Hold or Stabilize to fly by hand.' : 'Sticks are live in ' + mode + '.'}</div>`, { right: `<a data-go="live">Back to Live Operations ${I('chev')}</a>` })}</div></div>`; } } } });
})();
