/* Deep dives: mission/<id>, drone/<id>, alert/<id>. Every mission, drone and alert link lands here. */
(() => {
  const { UI, C, I } = VQ, D = VQ.ops, P = VQ.Plan;
  const seed = s => +String(s).replace(/\D/g, '') || 7;
  const head = (back, backGo, title, meta, pill, extra) => `<div class="row between wrap mb"><a data-go="${backGo}" class="row ink b" style="gap:4px">${I('chevl')}${back}</a>${extra || ''}</div><div class="inc-head"><div><h1>${title} ${pill}</h1><div class="meta">${meta.map(m => `<span>${m}</span>`).join('<i></i>')}</div></div></div>`;
  const ucOf = m => D.usecases[m.uc] || null;

  /* ---------- Mission ---------- */
  const mEvents = m => { const U = ucOf(m), a = D.alerts.find(x => x.mission === m.id); const t0 = m.start.split(' ')[1]; const ev = [[t0, 'Pre-flight checks passed, plan uploaded to ' + m.n + ' drone' + (m.n > 1 ? 's' : ''), 'good'], [t0.replace(/:\d\d/, ':0' + 4), 'Launch. Climb to separated altitudes', 'good'], [t0.replace(/:\d\d/, ':1' + 1), 'Entered the mission area, capture started', '']];
    if (a) ev.push([a.at.replace(' AM', ''), `${a.title} raised (${a.conf}%) and sent to the Command Center`, 'crit'], [a.at.replace(' AM', '').replace(/:(\d\d)/, (s, x) => ':' + String(+x + 1).padStart(2, '0')), 'Swarm re-tasked the nearest drone for a second pass', 'ai']);
    if (m.status === 'In Progress') ev.push(['08:42', `${m.pct}% complete, batteries on plan`, '']); if (m.status === 'Completed') ev.push(['—', 'All drones landed with reserve. Data uploaded, report generated', 'good']); if (m.status === 'Failed') ev.push(['16:48', 'Control link lost for 90 s in the valley; drones returned by the safe corridor. Mission marked failed at 30%', 'crit']); if (m.status === 'Paused') ev.push(['20:35', 'Paused by the operator: ATC notice at the port. Drones holding at the dock', 'crit']);
    return ev.map(e => ({ t: e[0], text: e[1], tone: e[2] })); };
  VQ.screen('mission', { ws: 'ops', rail: 'missions', fallback: 'missions', param: id => D.missions.find(m => m.id === id), title: c => c.item.name, crumbs: c => [['Missions', 'missions'], [c.item.id]],
    head: ({ item: m }) => head('Back to Missions', 'missions', m.name, [m.id, m.use, m.loc, `${m.n} drone${m.n > 1 ? 's' : ''} · ${m.drones}`, `Started ${m.start}`], UI.pill(m.status, D.statusTone[m.status]), `<div class="row">${UI.btn('Open Live', { ghost: 1, icon: 'play', go: 'live' })}${UI.btn('Mission Report', { ghost: 1, icon: 'file', go: 'reports' })}${m.status === 'In Progress' ? UI.btn('Pause Mission', { primary: 1, icon: 'x', toast: m.id + ' paused; drones holding position', done: 'Paused' }) : ''}</div>`),
    tabs: [['overview', 'Overview'], ['timeline', 'Timeline'], ['data', 'Data &amp; Findings'], ['drones', 'Drones'], ['risk', 'Risk &amp; Compliance']],
    views: {
      overview: { render: ({ item: m }) => { const U = ucOf(m), a = D.alerts.find(x => x.mission === m.id), ids = m.drones.replace(/ \(.*\)/, '').split(', ');
        return `<div class="grid g-2-1"><div class="card flush">${U ? VQ.MMap.render({ uc: U.key, h: 380, at: [m.pct / 100, m.pct / 100 * .95, m.pct / 100 * .9], layers: { area: 1, path: 1, sectors: 1, nfz: 1, drones: m.status === 'In Progress' }, showLayers: [['drones', 'Drones'], ['sectors', 'Sectors'], ['path', 'Flight path'], ['nfz', 'Geo-fence']] }) : UI.cam({ img: m.img, cls: 'wide', live: m.status === 'In Progress', label: m.name, foot: m.loc })}</div>
          <div class="col">${UI.card('Progress', `<div class="row"><div class="kpi-val" style="font-size:30px">${m.pct}%</div><div class="grow">${C.meter(m.pct, m.status === 'Failed' ? 'crit' : m.pct === 100 ? 'good' : '')}</div></div>${UI.statRow([[m.n, 'Drones'], [U ? U.alt + ' m' : '100 m', 'Altitude'], [U ? U.area : '1.8 km²', U ? U.areaLabel : 'Area'], [m.status === 'In Progress' ? '48 min' : U ? U.minutes + ' min' : '36 min', m.status === 'In Progress' ? 'Elapsed' : 'Flight time']])}<div class="card-note mt">${m.status === 'In Progress' ? `Estimated completion 09:15 AM. ${Math.round((100 - m.pct) / 100 * (U ? U.waypoints : 80))} waypoints to go.` : m.status === 'Completed' ? 'Closed on time. Report generated.' : m.status === 'Scheduled' ? 'Pre-flight checks start 30 minutes before launch.' : m.status === 'Failed' ? 'Link lost in the valley. See the timeline.' : 'Holding for an ATC notice.'}</div>`)}
            ${a ? UI.card('Alert on this mission', UI.list([{ thumb: a.img, title: a.title, titleTone: 'crit', sub: a.where, sub2: `${a.at} · confidence ${a.conf}%`, pill: UI.pill(a.sev.toUpperCase(), D.sevTone[a.sev]), go: `alert/${a.id}` }]), { icon: 'alert' }) : UI.card('Alerts', '<div class="card-note">No alerts on this mission.</div>')}</div></div>
        <div class="grid g3">${UI.card('Objective', `<div class="mb">${U ? U.objective : ({ Water: 'Patrol the main canal for unauthorized pumps, hoses and bank cuts, and put a number on the water lost.', 'Renewable Energy': 'Thermal survey of 42,000 panels for hot cells, string faults and soiling.', Security: 'Automated fence-line patrol with intrusion detection and gate activity logging.', 'Emergency Response': 'Map flooded area, find stranded people and check bridge and embankment damage.', Maritime: 'Night sweep of the container yard and quay for intrusion and unauthorised vessels.', 'Smart Cities': 'Orthomosaic and 3D model of 12 city blocks at 2 cm GSD.', Environment: 'Detect and track fire fronts with thermal, report to the forest control room.' })[m.use] || 'Routine survey.'}</div>${UI.kv([['route', 'Pattern', U ? U.pattern : 'Grid'], ['video', 'Payloads', U ? [...new Set(U.drones.flatMap(d => [d.p1, d.p2]))].join(', ') : 'RGB Camera, Thermal Camera'], ['sparkles', 'AI detectors', U ? U.detect.join(', ') : 'people, vehicles, thermal'], ['user', 'Planned by', D.user]])}`)}
          ${UI.card('Drones', UI.list(ids.map((id, i) => ({ icon: 'drone', tone: 'info', title: id + (U && U.drones[i] ? ' · ' + U.drones[i].role : ''), sub: m.status === 'In Progress' ? `In the air · battery ${(U && U.drones[i] ? U.drones[i].batt : 90) - 30}% · link strong` : m.status, go: `drone/${id}` }))) + '<div class="card-note mt">Select a drone for its full profile.</div>')}
          ${UI.card('Timeline', UI.vtimeline(mEvents(m).slice(-4)), { right: `<a data-go="mission/${m.id}/timeline">Full timeline ${I('chev')}</a>` })}</div>`; } },
      timeline: { render: ({ item: m }) => `<div class="grid g-2-1">${UI.card('Everything that happened', UI.vtimeline(mEvents(m)), { icon: 'clock' })}${UI.card('Time on each phase', C.hbars({ unit: 'min', items: [['Pre-flight', 6], ['Transit', 4], ['Capture', m.status === 'In Progress' ? Math.round(48 * .7) : 26], ['Re-tasking and second pass', m.alerts ? 5 : 0], ['Return and land', m.pct === 100 ? 4 : 0]].filter(r => r[1]).map(r => ({ label: r[0], value: r[1] })) }) + `<div class="card-note">${m.alerts ? 'The second pass added about 5 minutes and did not need operator input.' : 'No deviations from the plan.'}</div>`)}</div>` },
      data: { render: ({ item: m }) => { const U = ucOf(m), r = VQ.rng(seed(m.id)), img = U ? U.images : 4200, done = Math.round(img * m.pct / 100), det = m.alerts ? [['Thermal anomaly', 1, 'crit'], ['Tagged frames for review', 6, 'warn'], ['Vegetation patches', 14, 'info'], ['People (staff, badge confirmed)', 2, 'info']] : [['Tagged frames for review', 3, 'warn'], ['Vehicles', 12, 'info'], ['Objects on the asset', 0, 'info']];
        return UI.kpis([{ icon: 'video', bg: 'bg-info', value: VQ.fmt(done), label: 'Images captured' }, { icon: 'grid', bg: 'bg-good', value: Math.round((U ? U.coverage : 95) * m.pct / 100) + '%', label: 'Coverage so far' }, { icon: 'db', bg: 'bg-navy', value: Math.round((U ? U.dataGB : 180) * m.pct / 100) + ' GB', label: 'Data' }, { icon: 'sparkles', bg: 'bg-serious', value: det.reduce((a, d) => a + d[1], 0), label: 'AI detections' }], 'g4')
        + `<div class="grid g-2-1">${UI.card('Latest frames', `<div class="grid g3" style="margin:0;gap:8px">${(U ? { dam: ['th-eo.jpg', 'th-thermal.jpg', 'th-zoom.jpg'], highway: ['feed-highway.jpg', 'hw-cam-stalled-truck.jpg', 'hw-cam-corridor-1.jpg'], refinery: ['ref-feed-unit3.jpg', 'ref-thermal-column.jpg', 'ref-cam-column.jpg'] }[U.key] : [m.img, m.img, m.img]).map((f, i) => UI.cam({ img: f, cls: i === 1 && !/thermal/.test(f) ? 'thermal' : '', live: false, time: `08:${38 + i * 2} AM`, label: `Frame ${done - 2 + i}` })).join('')}</div><div class="card-note mt">Full-resolution imagery is on the drones and uploads after landing. Detections and clips stream live.</div>`)}
          ${UI.card('Detections', UI.list(det.map(d => ({ icon: d[2] === 'crit' ? 'alert' : 'sparkles', tone: d[2], title: d[0], meta: `<b class="ink">${d[1]}</b>`, go: d[2] === 'crit' && D.alerts.find(x => x.mission === m.id) ? `alert/${D.alerts.find(x => x.mission === m.id).id}` : null }))))}</div>
        <div class="grid g2">${UI.card('Images per minute', C.line({ h: 160, labels: Array.from({ length: 12 }, (_, i) => `+${i * 4}`), unit: 'img/min', series: [{ name: 'Images per minute', data: Array.from({ length: 12 }, (_, i) => Math.round(i < 2 ? 0 : 140 + (r() - .5) * 40)) , area: 1 }] }))}${UI.card('Deliverables', UI.list([['Orthomosaic', U ? U.gsd + ' cm GSD' : '2 cm GSD', 'On landing'], ['Thermal map', 'Radiometric, per-pixel °C', 'On landing'], ['Detection report', 'Every detection with frame and position', 'Live'], ['Flight log', 'Telemetry at 5 Hz', 'Live']].map(x => ({ icon: 'file', tone: 'info', title: x[0], sub: x[1], pill: UI.pill(x[2], x[2] === 'Live' ? 'good' : 'info') }))))}</div>`; } },
      drones: { render: ({ item: m }) => { const U = ucOf(m), ids = m.drones.replace(/ \(.*\)/, '').split(', ');
        return `<div class="grid g3">${ids.map((id, i) => { const d = U && U.drones[i], f = D.drones.find(x => x.id === id), b = (d ? d.batt : 90) - (m.status === 'In Progress' ? 30 : 0); return UI.card(id + (d ? ' · ' + d.role : ''), `<div class="row mb"><img src="assets/img/${f ? f.img : 'dr-multi.jpg'}" alt="" style="width:70px;height:40px;object-fit:contain"><div><div class="b ink">${d ? d.model : f ? f.model : 'DJI Matrice 30T'}</div><div class="small t2">${d ? d.sector : m.loc}</div></div></div>${UI.kv([['battery', 'Battery', `<span class="batt"><i style="--p:${b}%;--c:var(--${b < 40 ? 'warn' : 'good'})"></i>${b}%</span>`], ['gauge', 'Altitude', (U ? U.alt + i * 10 : 100) + ' m'], ['wifi', 'Link', 'Strong · -64 dBm'], ['video', 'Payload', d ? d.p1 + ' + ' + d.p2 : 'RGB + Thermal']])}<div class="row mt">${UI.btn('Full profile', { sm: 1, go: `drone/${id}` })}${UI.btn('Take Control', { sm: 1, primary: 1, go: 'control' })}</div>`, { icon: 'drone' }); }).join('')}</div>`; } },
      risk: { render: ({ item: m }) => { const U = ucOf(m); return `<div class="grid g2">${UI.card('Risks on this mission', UI.list((U ? U.risks : ['Flight over water: buoyancy kit fitted', 'Bird activity reported near the site', 'Public road within 50 m of the launch point']).map(r => ({ icon: 'alert', tone: 'warn', title: r }))))}${UI.card('Compliance', UI.kv([['shieldcheck', 'Airspace permission', 'Valid, ' + (U ? 'green zone' : 'green zone')], ['user', 'Pilot in command', 'Licensed, on duty'], ['lock', 'Geofence', 'Active, 0 breaches'], ['sun', 'Weather at launch', 'Inside limits'], ['file', 'Flight log', 'Recorded, retained 2 years']]))}</div>${UI.card('Fence and limit events', UI.vtimeline([{ t: '—', text: 'No fence contacts, no altitude exceedances, no link losses over 10 seconds.', tone: 'good' }]))}`; } },
    } });

  /* ---------- Drone ---------- */
  const flights = d => { const r = VQ.rng(seed(d.id)), out = []; for (let i = 0; i < 8; i++) out.push({ date: i === 0 && d.mission ? '16 Sep, ' + d.last.split(', ')[1] : `${15 - Math.floor(i / 2)} Sep, ${String(6 + (i * 3) % 10).padStart(2, '0')}:${i % 2 ? '40' : '05'}`, m: i === 0 && d.mission ? D.missions.find(x => x.id === d.mission).name : ['Perimeter Patrol', 'Urban Mapping block ' + (4 - i), 'Canal patrol', 'Solar farm survey', 'Bridge inspection'][i % 5], min: Math.round(24 + r() * 26), km: (7 + r() * 9).toFixed(1), det: Math.round(r() * 4), res: i === 0 && d.mission ? 'In progress' : 'Completed' }); return out; };
  VQ.screen('drone', { ws: 'ops', rail: 'fleet', fallback: 'fleet', param: id => D.drones.find(d => d.id === id) || (/^DR-\d{3}$/.test(id) ? { id, name: 'Unit ' + id.slice(-2), model: 'DJI Matrice 30T', type: 'Multirotor', status: 'In Mission', batt: 66, loc: 'On mission', last: 'Today, 07:30', hours: 240, img: 'dr-multi.jpg', mission: D.missions.find(m => m.drones.includes(id))?.id } : null), title: c => c.item.id, crumbs: c => [['Drone Fleet', 'fleet'], [c.item.id]],
    head: ({ item: d }) => head('Back to Drone Fleet', 'fleet', `${d.id} <span style="font-weight:500">${d.name}</span>`, [d.model, d.type, d.loc, `${d.hours} flight hours`], UI.pill(d.status, D.droneTone[d.status]), `<div class="row">${UI.btn('Run Diagnostics', { ghost: 1, icon: 'pulse', toast: 'Diagnostics started on ' + d.id })}${d.mission ? UI.btn('Take Control', { primary: 1, icon: 'gauge', go: 'control' }) : UI.btn('Assign to Mission', { primary: 1, icon: 'route', go: 'plan/swarm' })}</div>`),
    tabs: [['overview', 'Overview'], ['telemetry', 'Telemetry'], ['history', 'Flight History'], ['maintenance', 'Maintenance'], ['compliance', 'Compliance']],
    views: {
      overview: { render: ({ item: d }) => { const m = d.mission && D.missions.find(x => x.id === d.mission); return `<div class="grid g3"><div class="card"><img src="assets/img/${d.type === 'Multirotor' ? 'drone-big.jpg' : d.img}" alt="" style="width:100%;height:200px;object-fit:contain;background:#f1f5fb;border-radius:8px"><div class="b ink mt">${d.model}</div><div class="small t2">${d.type} · Inspection | Mapping | Surveillance</div></div>
          ${UI.card('Identity', UI.kv([['', 'Serial Number', '1581F6Q0' + d.id.slice(-3) + '4'], ['', 'Firmware', 'v7.02'], ['', 'Purchase Date', '12 Jan 2025'], ['', 'Total Flight Hours', d.hours + ' h'], ['', 'Last Flight', d.last], ['', 'Assigned To', 'Team Alpha'], ['', 'Payload now', d.mission ? 'RGB + Thermal' : 'None mounted']]))}
          <div class="col" style="gap:8px">${[['battery', 'Battery', d.batt == null ? 'Removed for service' : `${d.batt}% · est. ${Math.round(d.batt * .36)} min remaining · pack B, 212 cycles`], ['crosshair', 'GPS', '12 satellites · RTK fix'], ['wifi', 'Signal', '-68 dBm · strong'], ['db', 'Storage', '62% used · 124 GB free of 320 GB']].map(r => `<div class="chk ok" style="border-color:var(--line)">${I(r[0])}<div><b>${r[1]}</b><span>${r[2]}</span></div></div>`).join('')}</div></div>
        <div class="grid g-2-1">${m ? UI.card('Current mission', UI.list([{ thumb: m.img, title: m.name, sub: `${m.id} · ${m.use} · ${m.loc}`, sub2: `${m.pct}% complete`, pill: UI.pill(m.status, D.statusTone[m.status]), go: `mission/${m.id}` }]), { icon: 'route' }) : UI.card('Availability', `<div class="card-note">${d.status === 'In Maintenance' ? 'In the service centre. Back on 18 Sep.' : d.status === 'Charging' ? 'Charging at Base HQ, ready in about 40 minutes.' : 'Ready for the next mission.'}</div>`)}
          ${UI.card('Health', [['Airframe', 92], ['Battery', d.batt == null ? 60 : 87], ['Sensors', 90], ['Communication', 96]].map(h => `<div class="row" style="margin-bottom:8px"><span class="small" style="width:100px">${h[0]}</span><div class="grow">${C.meter(h[1], h[1] < 70 ? 'warn' : 'good')}</div><b class="ink small">${h[1]}%</b></div>`).join(''))}</div>`; } },
      telemetry: { render: ({ item: d }) => { const r = VQ.rng(seed(d.id)), n = 25, lab = Array.from({ length: n }, (_, i) => `+${i * 2}`); const b = Array.from({ length: n }, (_, i) => Math.round(96 - i * 1.2 - r() * 2)), alt = Array.from({ length: n }, (_, i) => i < 2 ? i * 60 : Math.round(118 + (r() - .5) * 10)), spd = Array.from({ length: n }, (_, i) => i < 2 ? 3 : Math.round(7 + (r() - .5) * 4)), sig = Array.from({ length: n }, (_, i) => Math.round(-60 - (i > 12 && i < 15 ? 22 : 0) - r() * 6));
        return `<div class="grid g2">${UI.card('Battery this flight', C.line({ h: 170, labels: lab, unit: '%', yMax: 100, limit: { v: 25, label: 'Reserve 25%' }, series: [{ name: 'Battery (%)', data: b, area: 1 }] }))}${UI.card('Altitude', C.line({ h: 170, labels: lab, unit: 'm AGL', yMax: 140, limit: { v: 120, label: 'Max 120 m' }, series: [{ name: 'Altitude (m AGL)', data: alt, color: 'var(--s3)' }] }))}</div>
        <div class="grid g2">${UI.card('Ground speed', C.line({ h: 150, labels: lab, unit: 'm/s', yMax: 15, series: [{ name: 'Speed (m/s)', data: spd, color: 'var(--s2)' }] }))}${UI.card('Control link', C.line({ h: 150, labels: lab, unit: 'dBm', yMin: -100, yMax: -40, series: [{ name: 'RSSI (dBm)', data: sig, color: 'var(--s7)' }] }) + '<div class="card-note">Dip at +26 to +28 min is the link shadow behind the abutment; the drone flew its stored plan.</div>')}</div>`; } },
      history: { render: ({ item: d }) => UI.card('Last 8 flights', UI.table([{ k: 'date', label: 'Date' }, { k: 'm', label: 'Mission' }, { k: 'min', label: 'Flight time', r: 1, fmt: v => v + ' min' }, { k: 'km', label: 'Distance', r: 1, fmt: v => v + ' km' }, { k: 'det', label: 'Detections', r: 1 }, { k: 'res', label: 'Result', fmt: v => UI.pill(v, v === 'Completed' ? 'good' : 'info') }], flights(d)) + `<div class="card-note mt">${d.hours} hours over the aircraft's life; ${Math.round(d.hours * .11)} this month.</div>`) },
      maintenance: { render: ({ item: d }) => `<div class="grid g2">${UI.card('Due', UI.table([{ k: 'w', label: 'Work' }, { k: 'd', label: 'Due' }, { k: 's', label: 'Status' }], [['50-hour inspection', 'In 38 flight hours', 'good', 'On schedule'], ['Propeller set replacement', '24 Sep 2026', 'warn', 'Due soon'], ['Battery pack B cycle check', '30 Sep 2026', 'good', 'On schedule'], ['Firmware v7.03', 'Available', 'info', 'Optional']].map(r => ({ w: `<b class="ink">${r[0]}</b>`, d: r[1], s: UI.pill(r[3], r[2]) }))))}${UI.card('History', UI.vtimeline([{ t: '02 Sep', text: 'IMU and compass calibrated; gimbal checked', tone: 'good' }, { t: '18 Aug', text: '200-hour service: motors, ESCs, arms inspected', tone: 'good' }, { t: '03 Jul', text: 'Propeller set replaced after a strike on landing', tone: 'crit' }, { t: '12 Jan 2025', text: 'Commissioned', tone: '' }]))}</div>` },
      compliance: { render: ({ item: d }) => UI.card('Certificates and records', UI.kv([['shieldcheck', 'Registration (UIN)', 'Valid'], ['file', 'Type certificate', 'Valid'], ['lock', 'Insurance', 'Valid to 31 Mar 2027'], ['user', 'Remote pilot licence on file', 'Yes'], ['wifi', 'Remote ID broadcast', 'Active'], ['clock', 'Flight logs retained', '2 years, 100% complete']])) },
    } });

  /* ---------- Alert ---------- */
  const X = { 'AL-0916-01': { what: 'Smoke rising from the top of distillation column C-301. Thermal shows the hottest point at the overhead flange, 410°C on the surface, and no open flame.', why: [['Overhead flange FL-3207 weeping onto hot insulation', 'Found on the 02 Sep inspection; work order still open', 72], ['Reflux flow down 9% since 08:14', 'Less reflux, hotter column top', 58], ['Wind from the south-west', 'Carries the plume across the pipe rack', 20]], next: 'Drone verified there is no flame. ERT is at the unit. The 10:00 inspection was brought forward and is flying now.', factors: [['thermo', 'Surface temperature', '410°C at the flange, 352°C column top'], ['cloud', 'Plume', 'Grey, no soot, drifting north-east'], ['users', 'People nearby', 'None on platforms 4–6'], ['clock', 'First seen', 'Fixed thermal camera, 08:37 AM']] },
    'AL-0916-02': { what: 'A band 6 m long on the downstream slope reads 3°C colder than the slope around it. That is the signature of water moving through the embankment.', why: [['Seepage through the embankment', 'Cold band lines up with the 140 m chainage drain', 66], ['Reservoir at 94% after the monsoon', 'Highest head of the year', 48], ['Old inspection note', 'Damp patch logged at the same chainage in 2024', 30]], next: 'DR-007 flew a second pass. The band is unchanged in 20 minutes: no fast change. The dam safety engineer has the frames and a site visit is booked for today.', factors: [['thermo', 'Temperature difference', '3.1°C below the surrounding slope'], ['ruler', 'Extent', '6 m by 1.5 m'], ['drop', 'Visible water', 'None in RGB'], ['clock', 'First seen', 'DR-007 thermal, 08:21 AM']] },
    'AL-0916-03': { what: 'A truck has been stationary in lane 2 of the southbound carriageway for over 3 minutes, with traffic passing on both sides.', why: [['Breakdown', 'Hazard lights on, no collision damage seen', 70], ['Queue building behind', 'Speed on the approach down 35%', 45], ['Narrow shoulder at Km 84.5', 'Truck could not pull clear', 40]], next: 'Position, clip and a still were sent to the highway control room at 07:57. The control room logged it as incident INC-2039 and dispatched a tow. DR-002 continues its patrol.', factors: [['truck', 'Vehicle', 'Heavy goods truck, lane 2'], ['clock', 'Stationary for', '3 min 40 s at detection'], ['car', 'Traffic', '1,260 vehicles/hour passing'], ['clock', 'First seen', 'DR-002 zoom camera, 07:56 AM']] } };
  VQ.screen('alert', { ws: 'ops', rail: 'alerts', fallback: 'alerts', param: id => D.alerts.find(a => a.id === id), title: c => c.item.title, crumbs: c => [['Incidents &amp; Alerts', 'alerts'], [c.item.id]],
    head: ({ item: a }) => `${head('Back to Alerts', 'alerts', a.title, [a.id, a.where, `Detected ${a.at}`, `Seen by ${a.src}`], UI.pill(a.sev.toUpperCase(), D.sevTone[a.sev]), `<div class="row">${UI.btn('Share', { ghost: 1, icon: 'share', toast: 'Alert link copied' })}${UI.btn('Mark as False Alarm', { ghost: 1, icon: 'x', toast: a.id + ' marked as false alarm and sent for model review' })}${UI.btn('Close Alert', { primary: 1, icon: 'checkc', toast: a.id + ' closed', done: 'Closed' })}</div>`)}`,
    tabs: [['overview', 'Overview'], ['evidence', 'Evidence'], ['analysis', 'Analysis'], ['response', 'Response'], ['related', 'Related']],
    views: {
      overview: { render: ({ item: a }) => { const x = X[a.id], m = D.missions.find(z => z.id === a.mission); return `<div class="grid g-2-1"><div class="col"><div class="grid g2" style="margin:0">${UI.cam({ img: a.img, label: a.src, time: a.at, boxes: [{ x: 30, y: 22, w: 40, h: 50, label: `${a.title} · ${a.conf}%`, tone: 'crit' }] })}${UI.cam({ img: a.img, cls: /thermal/.test(a.img) ? '' : 'thermal', label: 'Thermal view', time: a.at, extra: '<div class="scale"><b>Hot</b><em>Cool</em></div>' })}</div>
          <div class="insight"><span style="color:var(--violet)">${I('sparkles')}</span><div><b>What the drone saw</b><p>${x.what}</p></div></div><div class="insight" style="background:var(--good-bg)"><span style="color:var(--good)">${I('checkc')}</span><div><b>Where it stands now</b><p>${x.next}</p></div></div></div>
          <div class="col">${UI.card('Facts', UI.facts(x.factors), { icon: 'crosshair' })}${UI.card('Mission', UI.list([{ thumb: m.img, title: m.name, sub: `${m.id} · ${m.pct}% complete`, pill: UI.pill(m.status, D.statusTone[m.status]), go: `mission/${m.id}` }]))}${UI.card('Actions', UI.actions([{ icon: 'drone', tone: 'info', title: 'Send the nearest drone to verify', sub: 'Closest drone is 4 minutes away', btn: 'Dispatch', primary: 1 }, { icon: 'users', tone: 'violet', title: 'Notify the site team', sub: 'Clip and position attached', btn: 'Notify' }, { icon: 'play', tone: 'good', title: 'Watch live', sub: m.name, btn: 'Open', go: 'live' }]))}</div></div>`; } },
      evidence: { render: ({ item: a }) => { const t = a.at.replace(' AM', '').split(':'); return `${UI.card('Frames around the detection', `<div class="grid g3" style="margin:0;gap:8px">${[-2, -1, 0, 1, 2, 3].map(k => UI.cam({ img: a.img, live: false, cls: k % 2 ? 'thermal' : '', time: `${t[0]}:${String(+t[1] + k).padStart(2, '0')} AM`, label: k === 0 ? 'Detection frame' : k < 0 ? 'Before' : 'After', boxes: k >= 0 ? [{ x: 30 + k, y: 22, w: 40, h: 50, label: `${a.conf - Math.abs(k) * 2}%`, tone: 'crit' }] : [] })).join('')}</div>`, { right: `${UI.btn('Save Clip', { sm: 1, icon: 'clip', toast: 'Clip saved to the alert record' })}${UI.btn('Export Evidence Pack', { sm: 1, icon: 'download', toast: 'Evidence pack exported: frames, telemetry, detections' })}` })}
        <div class="grid g2 mt">${UI.card('What the model saw', UI.table([{ k: 'o', label: 'Detection' }, { k: 'c', label: 'Confidence', r: 1 }, { k: 'n', label: 'Note' }], [{ o: a.title, c: a.conf + '%', n: 'Primary subject; stable over 3 frames' }, { o: 'Position', c: '99%', n: 'RTK fix, ±3 cm' }, { o: 'Asset match', c: '97%', n: 'Matched to the asset register' }]))}${UI.card('Evidence pack', UI.kv([['video', 'Frames', '8 stills and a 30-second clip'], ['mappin', 'Position', 'RTK, ±3 cm'], ['clock', 'Time stamps', 'Drone clock, synced to GPS'], ['lock', 'Integrity', 'SHA-256 hash on every file']]))}</div>`; } },
      analysis: { render: ({ item: a }) => { const x = X[a.id]; return `<div class="grid g2">${UI.card('Probable cause', UI.factors(x.why.map(w => ({ title: w[0], text: w[1], pct: w[2] }))) + '<div class="card-note mt">Bars are the model’s estimate of how much each factor contributed. They overlap, so they do not add to 100.</div>', { icon: 'sparkles' })}${UI.card('Confidence', `<div class="row mb"><div class="kpi-val" style="font-size:34px">${a.conf}%</div><div class="t2">Detection confidence</div></div>` + UI.steps(['Seen in 3 consecutive frames.', 'Thermal and visual agree.', a.id === 'AL-0916-03' ? 'Speed on the approach corroborates it.' : 'Matches a known pattern for this asset type.', 'Human review: pending.']) + `<div class="row mt">${UI.btn('Confirm', { sm: 1, primary: 1, toast: a.id + ' confirmed by ' + D.user, done: 'Confirmed' })}${UI.btn('Reject', { sm: 1, toast: a.id + ' rejected and sent for model review' })}</div>`)}</div>`; } },
      response: { render: ({ item: a }) => { const t = a.at.replace(' AM', ''); const add = (s, k) => { const [h, m] = s.split(':').map(Number), x = m + k; return `${String(h + Math.floor(x / 60)).padStart(2, '0')}:${String(x % 60).padStart(2, '0')}`; }; return `<div class="grid g2">${UI.card('What was done', UI.vtimeline([{ t, text: `<b>${a.title}</b> detected by ${a.src}`, tone: 'crit' }, { t: add(t, 1), text: 'Alert sent to the Command Center with clip and position', who: 'Automatic' }, { t: add(t, 2), text: 'Nearest drone re-tasked for a second pass', who: 'Swarm · automatic', tone: 'ai' }, { t: add(t, 3), text: a.id === 'AL-0916-03' ? 'Highway control room notified; tow dispatched' : 'Site team notified', who: 'Control room · ' + D.user }, { t: add(t, 9), text: 'Second pass complete, detection confirmed', tone: 'good' }]), { icon: 'clock' })}${UI.card('Against target', UI.table([{ k: 's', label: 'Step' }, { k: 'a', label: 'This alert' }, { k: 't', label: 'Target' }, { k: 'p', label: 'Result' }], [['Detect to alert', '42 sec', '60 sec', 'good'], ['Alert to verification', '9 min', '10 min', 'good'], ['Alert to site team notified', '3 min', '5 min', 'good']].map(r => ({ s: r[0], a: r[1], t: r[2], p: UI.pill('Within target', r[3]) }))) + `<div class="row mt">${UI.btn('Escalate to shift supervisor', { sm: 1, toast: 'Escalated' })}</div>`)}</div>`; } },
      related: { render: ({ item: a }) => { const m = D.missions.find(z => z.id === a.mission); return `<div class="grid g2">${UI.card('Other alerts today', UI.list(D.alerts.filter(z => z.id !== a.id).map(z => ({ thumb: z.img, title: z.title, sub: z.where, meta: z.at, pill: UI.pill(z.sev.toUpperCase(), D.sevTone[z.sev]), go: `alert/${z.id}` }))))}${UI.card('Where this shows up', UI.list([{ icon: 'route', tone: 'info', title: m.name, sub: 'The mission that raised it', go: `mission/${m.id}` }, { icon: 'drone', tone: 'info', title: a.src.split(' ')[0], sub: 'The drone that saw it', go: `drone/${a.src.match(/DR-\d{3}/) ? a.src.match(/DR-\d{3}/)[0] : 'DR-006'}` }, { icon: 'bars', tone: 'info', title: 'Data &amp; Analytics', sub: 'Detections by type, 30 days', go: 'analytics' }]))}</div>`; } },
    } });
})();
