/* Drone Fleet (mockup 03) and Payloads & Sensors */
(() => {
  const { UI, C, I } = VQ, D = VQ.ops, F = D.fleet;
  const batt = b => b == null ? '—' : `<span class="batt"><i style="--p:${b}%;--c:var(--${b < 50 ? 'warn' : 'good'})"></i>${b}%</span>`;

  VQ.screen('fleet', { ws: 'ops', title: 'Drone Fleet', sub: 'One fleet. Any mission. Always ready.', headRight: () => UI.btn('Add Drone', { primary: 1, icon: 'plus', toast: 'Drone registration form opened (demo)' }),
    views: { main: { render: () => { const d = D.drones.find(x => x.id === (VQ.state.dr || 'DR-001')), tab = VQ.state.dt || 'overview', f = VQ.state.ff || 'all', rows = D.drones.filter(x => f === 'all' || x.status === f);
      const body = { overview: () => `<div class="grid g3" style="margin:0"><div style="text-align:center"><img src="assets/img/${d.type === 'Multirotor' ? 'drone-big.jpg' : d.img}" alt="" style="width:100%;max-height:190px;object-fit:contain;background:#f1f5fb;border-radius:8px"><div class="small t2 mt">${d.type} · Inspection | Mapping | Surveillance</div></div>
          ${UI.kv([['', 'Model', d.model], ['', 'Serial Number', '1581F6Q0' + d.id.slice(-3) + '4'], ['', 'Firmware', 'v7.02'], ['', 'Purchase Date', '12 Jan 2025'], ['', 'Total Flight Hours', d.hours + ' h'], ['', 'Last Flight', d.last], ['', 'Current Location', d.loc], ['', 'Assigned To', 'Team Alpha']])}
          <div class="col" style="gap:8px">${[['battery', 'Battery', d.batt == null ? 'Removed for service' : d.batt + '% · est. ' + Math.round(d.batt * .36) + ' min remaining'], ['crosshair', 'GPS', '12 satellites · RTK fix'], ['wifi', 'Signal Strength', '-68 dBm · strong'], ['db', 'Storage', '62% used · 124 GB free of 320 GB']].map(r => `<div class="chk ok" style="border-color:var(--line)">${I(r[0])}<div><b>${r[1]}</b><span>${r[2]}</span></div></div>`).join('')}${d.mission ? UI.btn('View in Live Operations', { sm: 1, primary: 1, go: 'live' }) : UI.btn('Assign to Mission', { sm: 1, primary: 1, go: 'plan/swarm' })}</div></div>`,
        sensors: () => UI.table([{ k: 's', label: 'Sensor' }, { k: 'st', label: 'Status' }, { k: 'c', label: 'Last calibrated' }, { k: 'n', label: 'Note' }], [['IMU', 'OK', '02 Sep 2026', 'Within tolerance'], ['Compass', 'OK', '02 Sep 2026', ''], ['Obstacle sensing (6 directions)', 'OK', '02 Sep 2026', ''], ['Gimbal', d.id === 'DR-003' ? 'Check' : 'OK', '28 Aug 2026', d.id === 'DR-003' ? 'Drift 0.4° on yaw; recalibrate' : ''], ['RTK module', 'OK', '02 Sep 2026', '']].map(r => ({ s: `<b class="ink">${r[0]}</b>`, st: UI.pill(r[1], r[1] === 'OK' ? 'good' : 'warn'), c: r[2], n: r[3] }))),
        maintenance: () => UI.table([{ k: 'w', label: 'Work' }, { k: 'd', label: 'Due' }, { k: 's', label: 'Status' }], [['50-hour inspection', 'In 38 flight hours', 'good', 'On schedule'], ['Propeller set replacement', '24 Sep 2026', 'warn', 'Due soon'], ['Battery pack B cycle check (212 cycles)', '30 Sep 2026', 'good', 'On schedule'], ['Firmware v7.03', 'Available', 'info', 'Optional']].map(r => ({ w: `<b class="ink">${r[0]}</b>`, d: r[1], s: UI.pill(r[3], r[2]) }))),
        history: () => UI.table([{ k: 'd', label: 'Date' }, { k: 'm', label: 'Mission' }, { k: 't', label: 'Flight time', r: 1 }, { k: 'k', label: 'Distance', r: 1 }, { k: 'r', label: 'Result' }], [['16 Sep, 07:12', 'M-2026-001 North Ridge Dam Inspection', '48 min so far', '9.6 km', 'In progress'], ['15 Sep, 16:05', 'Perimeter Patrol', '31 min', '11.2 km', 'Completed'], ['15 Sep, 09:40', 'Urban Mapping block 4', '36 min', '13.8 km', 'Completed'], ['14 Sep, 08:00', 'Urban Mapping block 3', '34 min', '12.9 km', 'Completed']].map(r => ({ d: r[0], m: r[1], t: r[2], k: r[3], r: UI.pill(r[4], r[4] === 'Completed' ? 'good' : 'info') }))),
        compliance: () => UI.kv([['shieldcheck', 'Registration (UIN)', 'Valid'], ['file', 'Type certificate', 'Valid'], ['lock', 'Insurance', 'Valid to 31 Mar 2027'], ['user', 'Remote pilot licence on file', 'Yes'], ['wifi', 'Remote ID broadcast', 'Active']]),
        documents: () => UI.list([['Airframe manual', 'PDF · rev 4'], ['Maintenance log', 'Updated 02 Sep 2026'], ['Insurance certificate', 'PDF'], ['Calibration certificates', '5 files']].map(r => ({ icon: 'file', tone: 'info', title: r[0], sub: r[1], pill: `<a data-act="${r[0]} opened (demo)">View</a>` }))) }[tab]();
      return UI.kpis([{ icon: 'drone', bg: 'bg-navy', value: F.total, label: 'Total Drones', delta: { text: `${F.active} active · ${F.inactive} inactive · ${F.maintenance} in maintenance` } }, { icon: 'refresh', bg: 'bg-good', value: F.availability + '%', label: 'Fleet Availability', delta: { dir: 'up', value: '+6%', text: 'vs. last month', good: true } }, { icon: 'wrench', bg: 'bg-serious', value: F.inMaint, label: 'In Maintenance', delta: { text: '2 under 24 hrs · 3 over 24 hrs' } },
        { icon: 'battery', bg: 'bg-info', value: F.battHealth + '%', label: 'Avg. Battery Health', delta: { dir: 'up', value: '+4%', text: 'vs. last month', good: true } }, { icon: 'cal', bg: 'bg-violet', value: F.flightHoursWeek, label: 'Flight Hours (week)', delta: { dir: 'up', value: '+18%', text: 'vs. last week', good: true } }, { icon: 'shieldcheck', bg: 'bg-good', value: F.compliance + '%', label: 'Compliance Status', delta: { dot: 'good', text: 'All certificates valid' } }], 'g6')
      + `<div class="grid g-3-1">${UI.card('Drone Fleet', UI.seg('ff', [['all', `All Drones (${F.total})`], ['In Mission', 'In Mission'], ['Standby', 'Standby'], ['Charging', 'Charging'], ['In Maintenance', 'Maintenance']], f) + `<div class="tbl-wrap mt"><table class="tbl"><thead><tr><th></th><th>ID / Name</th><th>Model</th><th>Type</th><th>Status</th><th>Battery</th><th>Location</th><th>Last Flight</th><th class="r">Hours</th></tr></thead><tbody>${rows.map(x => `<tr class="click" data-set="dr=${x.id}" style="${x.id === d.id ? 'background:var(--blue-50)' : ''}"><td><img src="assets/img/${x.img}" alt="" style="width:48px;height:26px;object-fit:contain"></td><td><b style="color:var(--blue)">${x.id}</b><br><a data-go="drone/${x.id}" class="small">Deep dive ${I('chev')}</a></td><td>${x.model}</td><td>${x.type}</td><td>${UI.pill(x.status, D.droneTone[x.status])}</td><td>${batt(x.batt)}</td><td>${x.loc}</td><td>${x.last}</td><td class="r">${x.hours} h</td></tr>`).join('')}</tbody></table></div><div class="card-note mt">Showing ${rows.length} of ${F.total} drones. Select a row for its detail below.</div>`)}
        <div class="col">${UI.card('Fleet Composition', C.donut({ size: 120, thick: 18, center: { v: F.total, l: 'Drones' }, items: F.types.map(t => ({ label: t[0], value: t[1] })) }))}
          ${UI.card('Fleet Health', [['Airframe Health', 92], ['Battery Health', 87], ['Sensor Health', 90], ['Communication', 96], ['Firmware Compliance', 100]].map(h => `<div class="row" style="margin-bottom:8px"><span class="small" style="width:132px">${h[0]}</span><div class="grow">${C.meter(h[1], 'good')}</div><b class="ink small">${h[1]}%</b></div>`).join(''))}</div></div>
      <div class="card mb"><div class="row between wrap mb"><div class="row"><span class="kpi-val">${d.id}</span><span style="font-size:16px">${d.name}</span>${UI.pill(d.status, D.droneTone[d.status])}${UI.btn('Full profile', { sm: 1, go: `drone/${d.id}` })}</div>${UI.seg('dt', [['overview', 'Overview'], ['sensors', 'Sensors'], ['maintenance', 'Maintenance'], ['history', 'Flight History'], ['compliance', 'Compliance'], ['documents', 'Documents']], tab)}</div>${body}</div>
      <div class="grid g2">${UI.card('Location Distribution', C.hbars({ items: F.locations.map(l => ({ label: l[0], value: l[1], icon: 'mappin' })), unit: 'drones' }) + `<div class="card-note">Adds up to ${F.total} drones.</div>`)}${UI.card('Quick Actions', UI.quick([{ icon: 'pulse', label: 'Run Diagnostics' }, { icon: 'route', label: 'Assign to Mission', go: 'plan/swarm' }, { icon: 'crosshair', label: 'Calibrate Sensors' }, { icon: 'file', label: 'View Flight Logs' }, { icon: 'download', label: 'Update Firmware' }, { icon: 'x', label: 'Retire Drone' }]))}</div>`; } } } });

  VQ.screen('payloads', { ws: 'ops', title: 'Payloads &amp; Sensors', sub: 'What the fleet can carry, what fits what, and what is due for calibration.', views: { main: { render: () => { const models = ['DJI Matrice 350', 'Autel EVO Max', 'DJI Mavic 3T', 'WingtraOne', 'eBee X', 'Volansi VOLY'], fit = { rgb: [1, 1, 1, 1, 1, 0], thermal: [1, 1, 1, 0, 0, 0], lidar: [1, 0, 0, 1, 0, 0], multi: [1, 0, 1, 1, 1, 0], gas: [1, 1, 0, 0, 0, 0], zoom: [1, 1, 1, 0, 0, 0], speaker: [1, 1, 1, 0, 0, 0], drop: [1, 0, 0, 0, 0, 1] };
      const total = D.payloads.reduce((a, p) => a + p.stock, 0);
      return UI.kpis([{ icon: 'video', bg: 'bg-info', value: total, label: 'Payloads in Inventory', delta: { text: `${D.payloads.length} types` } }, { icon: 'drone', bg: 'bg-good', value: 23, label: 'Mounted Now' }, { icon: 'crosshair', bg: 'bg-serious', value: 4, label: 'Calibration Due (7 days)' }, { icon: 'video', bg: 'bg-navy', value: D.home.cameras, label: 'Fixed Cameras Linked', delta: { text: `${D.home.camOnline} online` } }], 'g4')
      + `<div class="grid g-2-1">${UI.card('Payload inventory', `<div class="pcat">${D.payloads.map(p => `<div class="pc" data-go="plan/payload"><img src="assets/img/${p.img}" alt=""><b>${p.name}</b><span>${p.text}</span><div class="tags"><i class="tagc" style="font-style:normal">${p.stock} in stock</i><i class="tagc" style="font-style:normal">${p.cat}</i></div></div>`).join('')}</div><div class="card-note mt">Select a payload to configure it on a mission.</div>`)}
        <div class="col">${UI.card('Calibration due', UI.list([{ icon: 'thermo', tone: 'warn', title: 'Thermal Camera · unit T-07', sub: 'Blackbody check due 18 Sep', pill: UI.pill('2 days', 'warn') }, { icon: 'crosshair', tone: 'warn', title: 'LiDAR · unit L-02', sub: 'Boresight calibration due 19 Sep', pill: UI.pill('3 days', 'warn') }, { icon: 'cloud', tone: 'warn', title: 'Gas Sensor · unit G-01', sub: 'Span gas check due 21 Sep', pill: UI.pill('5 days', 'warn') }, { icon: 'leaf', tone: 'warn', title: 'Multispectral · unit M-04', sub: 'Reflectance panel due 22 Sep', pill: UI.pill('6 days', 'warn') }]))}
          ${UI.card('Use this week', C.hbars({ unit: 'flights', items: [['RGB Camera', 96], ['Thermal Camera', 58], ['Zoom Camera', 33], ['LiDAR', 14], ['Multispectral', 12], ['Gas Sensor', 9]].map(r => ({ label: r[0], value: r[1] })) }))}</div></div>
      ${UI.card('What fits what', `<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Payload</th>${models.map(m => `<th>${m}</th>`).join('')}</tr></thead><tbody>${D.payloads.map(p => `<tr><td><b class="ink">${p.name}</b></td>${fit[p.id].map(v => `<td>${v ? `<span style="color:var(--good);display:inline-flex;width:16px;height:16px">${I('check')}</span>` : '<span class="muted">–</span>'}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="card-note mt">Mission Planning uses this table: it only offers payloads the chosen drone can carry and power.</div>`, { cls: 'mb' })}`; } } } });
})();
