/* Geofencing & Airspace, Incidents & Alerts, Data & Analytics, Reports, Administration */
(() => {
  const { UI, C, I } = VQ, D = VQ.ops, P = VQ.Plan;

  VQ.screen('airspace', { ws: 'ops', title: 'Geofencing &amp; Airspace', sub: 'Where drones may fly, where they may not, and the permissions behind every mission.', views: { main: { render: () => { const uc = D.uc().key;
    return UI.kpis([{ icon: 'ban', bg: 'bg-crit', value: 14, label: 'No-Fly Zones' }, { icon: 'alert', bg: 'bg-warn', value: 9, label: 'Restricted Areas' }, { icon: 'route', bg: 'bg-good', value: 11, label: 'Safe Corridors' }, { icon: 'shieldcheck', bg: 'bg-info', value: 6, label: 'Permissions Valid Today' }, { icon: 'octagon', bg: 'bg-serious', value: 1, label: 'Advisory Active' }], 'g5')
    + `<div class="grid g-2-1"><div class="card"><div class="card-h"><h3>Airspace map · ${D.project().name}</h3><div class="right"><span class="small">Switch project in the top bar</span></div></div>${VQ.MMap.render({ uc, h: 430, labels: false, layers: { nfz: 1, safe: 1, elz: 1, obst: 1, area: 1, drones: 0 }, showLayers: [['nfz', 'No-fly and restricted'], ['safe', 'Safe corridors'], ['elz', 'Emergency landing zones'], ['obst', 'Obstacles'], ['area', 'Mission areas'], ['path', 'Planned routes']] })}</div>
      <div class="col">${UI.card('Permissions', UI.table([{ k: 's', label: 'Site' }, { k: 'z', label: 'Zone' }, { k: 'v', label: 'Valid' }], [['North Ridge Dam', 'good', 'Green', 'Today 06:00 – 18:00'], ['NH-44 Km 78–92', 'good', 'Green', 'Today 06:00 – 18:00'], ['Refinery', 'warn', 'Yellow · site approval held', 'Standing, renew 30 Sep'], ['Port, Visakhapatnam', 'warn', 'Yellow · ATC notice', 'Tonight 20:00 – 02:00']].map(r => ({ s: `<b class="ink">${r[0]}</b>`, z: UI.pill(r[2], r[1]), v: r[3] }))) + '<div class="card-note mt">Permissions are checked again at Mission Readiness, not only when the plan is saved.</div>', { icon: 'shieldcheck' })}
        ${UI.card('Advisories', P.chk('warn', 'Helicopter movement near NH-44 Km 90', 'Trauma centre helipad active 09:00 – 10:00 AM. The corridor patrol holds short of Km 89 until it clears.') + '<div class="mt"></div>' + P.chk('ok', 'No temporary restrictions at the other sites', 'Last checked 08:40 AM.'))}</div></div>
    <div class="grid g2">${UI.card('Zone register', UI.table([{ k: 'n', label: 'Zone' }, { k: 't', label: 'Type' }, { k: 'r', label: 'Rule' }, { k: 'b', label: 'Breaches (30 days)', r: 1 }], [['Dam control building and switchyard', 'crit', 'No-fly', 'Never enter', 0], ['Village north-east of the dam', 'warn', 'Restricted', '60 m minimum altitude', 0], ['Trauma centre helipad, Km 90', 'crit', 'No-fly', '500 m radius when active', 1], ['Jadcherla town', 'warn', 'Restricted', '90 m minimum altitude', 0], ['Refinery flare stack', 'crit', 'No-fly', '60 m radius', 0], ['Refinery tank farm', 'warn', 'Restricted', 'No overflight below 40 m', 2]].map(r => ({ n: `<b class="ink">${r[0]}</b>`, t: UI.pill(r[2], r[1]), r: r[3], b: r[4] }))) + `<div class="row mt">${UI.btn('Add Zone', { sm: 1, icon: 'plus', toast: 'Draw the new zone on the map (demo)' })}${UI.btn('Import KML / GeoJSON', { sm: 1, toast: 'Import dialog opened (demo)' })}</div>`)}
      ${UI.card('Fence events, last 30 days', C.bars({ h: 170, labels: ['Buffer touched', 'Auto re-route', 'Hover and alert', 'Breach'], series: [{ name: 'Events', data: [21, 9, 4, 3] }], valueLabels: 1, unit: 'events' }) + '<div class="card-note">All 3 breaches were under 10 m and under 5 seconds. Two were at the refinery tank farm in gusty wind; the buffer there is now 30 m.</div>')}</div>`; } } } });

  VQ.screen('alerts', { ws: 'ops', title: 'Incidents &amp; Alerts', sub: 'What the drones and cameras found, with the evidence and the next step.', views: { main: { render: () => { const a = D.alerts.find(x => x.id === VQ.state.al) || D.alerts.find(x => x.mission === D.project().live) || D.alerts[0], m = D.missions.find(x => x.id === a.mission);
    const recent = [['07:42 AM', 'Possible liquid leak · pipeline corridor', 'Closed · stain confirmed as rainwater'], ['06:58 AM', 'Person inside the dam exclusion area', 'Closed · dam staff, badge confirmed'], ['06:12 AM', 'Drone DR-012 low battery on the canal patrol', 'Closed · returned, battery swapped'], ['Yesterday', 'Geofence buffer touched · refinery tank farm', 'Closed · gust, auto re-routed']];
    return UI.kpis([{ icon: 'alert', bg: 'bg-crit', value: 3, label: 'Active Alerts', delta: { text: '1 critical · 1 high · 1 medium' } }, { icon: 'checkc', bg: 'bg-good', value: 9, label: 'Closed Today' }, { icon: 'clock', bg: 'bg-info', value: '42 sec', label: 'Detect to Alert' }, { icon: 'shieldcheck', bg: 'bg-navy', value: '8%', label: 'False Alarm Rate', delta: { dir: 'down', value: '−3 pts', text: 'vs. last month', good: true } }], 'g4')
    + `<div class="grid g-1-2">${UI.card('Active alerts', `<div class="list">${D.alerts.map(x => `<div class="li click" data-set="al=${x.id}" style="${x.id === a.id ? 'background:var(--blue-50)' : ''}"><img class="li-thumb" src="assets/img/${x.img}" alt=""><div class="li-body"><div class="li-title ${x.sev === 'critical' ? 'crit' : 'warn'}">${x.title}</div><div class="li-sub">${x.where}</div><div class="li-sub">${x.at} · ${x.src}</div></div><div class="li-meta">${UI.pill(x.sev[0].toUpperCase() + x.sev.slice(1), D.sevTone[x.sev])}<a data-go="alert/${x.id}" class="small">Deep dive ${I('chev')}</a></div></div>`).join('')}</div><hr class="sep"><div class="b ink small mb">Closed recently</div>${UI.list(recent.map(r => ({ icon: 'checkc', tone: 'good', title: r[1], sub: r[2], meta: r[0] })))}`)}
      <div class="card"><div class="row between wrap mb"><div><div class="kpi-val">${a.title}</div><div class="t2">${a.where}</div></div><div class="row">${UI.pill(a.sev.toUpperCase(), D.sevTone[a.sev])}${UI.btn('Open deep dive', { sm: 1, primary: 1, go: `alert/${a.id}` })}</div></div>
        <div class="grid g2" style="margin:0 0 10px">${UI.cam({ img: a.img, label: a.src, time: a.at, boxes: [{ x: 30, y: 22, w: 40, h: 50, label: `${a.title} · ${a.conf}%`, tone: 'crit' }] })}${UI.cam({ img: a.img, cls: /thermal/.test(a.img) ? '' : 'thermal', label: 'Thermal view', time: a.at, extra: '<div class="scale"><b>Hot</b><em>Cool</em></div>' })}</div>
        <div class="grid g2" style="margin:0">${UI.kv([['clock', 'Detected', `${a.at}, ${D.date}`], ['shieldcheck', 'Confidence', a.conf + '%'], ['route', 'Mission', `${m.id} · ${m.name}`], ['drone', 'Seen by', a.src]])}<div><div class="insight"><span style="color:var(--violet)">${I('sparkles')}</span><div><b>What it means</b><p>${a.text}</p></div></div>${UI.actions([{ icon: 'drone', tone: 'info', title: 'Send the nearest drone to verify', sub: 'Closest drone is 4 minutes away', btn: 'Dispatch', primary: 1 }, { icon: 'users', tone: 'violet', title: 'Notify the site team', sub: 'Clip and position attached', btn: 'Notify' }, { icon: 'play', tone: 'good', title: 'Open the mission live', sub: m.name, btn: 'Open', go: 'live' }])}</div></div></div></div>`; } } } });

  VQ.screen('analytics', { ws: 'ops', title: 'Data &amp; Analytics', sub: 'What the fleet flew, what it captured and what it found, across every use case.', views: { main: { render: () => { const days = Array.from({ length: 14 }, (_, i) => `${i + 3} Sep`);
    return UI.kpis([{ icon: 'route', bg: 'bg-info', value: 548, label: 'Missions (30 days)', delta: { dir: 'up', value: '+27%', text: 'vs. last month', good: true } }, { icon: 'clock', bg: 'bg-violet', value: '1,140', unit: 'hrs', label: 'Flight Hours' }, { icon: 'shieldcheck', bg: 'bg-good', value: '98%', label: 'Mission Success' }, { icon: 'db', bg: 'bg-navy', value: '6.2', unit: 'TB', label: 'Data Captured' }, { icon: 'sparkles', bg: 'bg-serious', value: 312, label: 'AI Detections', delta: { text: '92% confirmed on review' } }], 'g5')
    + `<div class="grid g2">${UI.card('Missions per day, by outcome', C.bars({ h: 200, stacked: 1, labels: days, unit: 'missions', series: [{ name: 'Completed', data: VQ.series(14, 34, 8, 3).map(Math.round), color: 'var(--s3)' }, { name: 'Completed late', data: VQ.series(14, 3, 3, 5).map(v => Math.max(0, Math.round(v))), color: 'var(--s4)' }, { name: 'Aborted or failed', data: VQ.series(14, 1, 2, 9).map(v => Math.max(0, Math.round(v))), color: 'var(--s8)' }] }))}
      ${UI.card('Missions by use case (30 days)', C.hbars({ unit: 'missions', items: [['Infrastructure inspection', 142], ['Security and perimeter', 118], ['Highway corridor patrol', 96], ['Oil and gas assets', 64], ['Water and canals', 58], ['Mapping and survey', 41], ['Emergency response', 29]].map(r => ({ label: r[0], value: r[1] })) }) + '<div class="card-note">Adds up to the 548 missions above. One platform, seven kinds of work.</div>')}</div>
    <div class="grid g3">${UI.card('Detections by type', C.donut({ size: 130, thick: 20, center: { v: 312, l: 'Detections' }, items: [['Thermal anomalies', 98], ['Vehicles and objects', 84], ['People', 52], ['Asset defects', 46], ['Smoke, water, other', 32]].map(r => ({ label: r[0], value: r[1] })) }))}
      ${UI.card('Fleet utilisation', C.line({ h: 170, labels: days, unit: '%', yMax: 100, series: [{ name: 'Drones flying at least once (%)', data: VQ.series(14, 71, 10, 7).map(Math.round), area: 1 }] }) + '<div class="card-note">Average 71%. Fixed-wing drones are the least used, at 48%.</div>')}
      ${UI.card('What to act on', UI.insight('battery', 'warn', 'Battery swaps cost 38 flight hours a month', 'A second charging dock at North Ridge removes most of it.', 'fleet') + UI.insight('route', 'blue', 'Swarm missions finish 41% faster', 'Three-drone area missions against single-drone missions of the same size.', 'swarm') + UI.insight('alert', 'crit', 'Refinery tank farm causes most fence events', 'Buffer raised to 30 m; review after two weeks.', 'airspace'))}</div>`; } } } });

  VQ.screen('reports', { ws: 'ops', title: 'Reports', sub: 'Mission, fleet and compliance reports, on demand or on a schedule.', views: { main: { render: () => `<div class="uc-grid mb">${[['route', 'Mission report', 'Route flown, coverage, detections and evidence for one mission.', 'Per mission'], ['drone', 'Fleet health', 'Availability, battery health, maintenance due.', 'Weekly'], ['shieldcheck', 'Airspace and compliance', 'Permissions, fence events, pilot and aircraft records.', 'Monthly'], ['sparkles', 'Detection summary', 'What the AI found, by site and type, with review outcomes.', 'Weekly'], ['bars', 'Operations summary', 'Missions, hours, success rate and data captured.', 'Daily'], ['db', 'Data delivery', 'Orthomosaics, point clouds and thermal maps handed over.', 'Per mission']].map(r => `<div class="card uc"><div class="top"><span style="width:22px;height:22px;color:var(--blue)">${I(r[0])}</span><h4>${r[1]}</h4></div><p>${r[2]}</p><div class="foot">${UI.pill(r[3], 'info')}${UI.btn('Generate', { sm: 1, toast: r[1] + ' is being generated' })}</div></div>`).join('')}</div>
    <div class="grid g-2-1">${UI.card('Recent reports', UI.table([{ k: 'n', label: 'Report' }, { k: 'p', label: 'Period' }, { k: 'g', label: 'Generated' }, { k: 'f', label: 'Format' }, { k: 'd', label: '' }], [['Mission report · M-2026-006 Perimeter Patrol', '16 Sep', 'Today, 06:48 AM', 'PDF'], ['Operations summary', '15 Sep', 'Today, 06:00 AM', 'PDF'], ['Mission report · M-2026-009 Urban Mapping', '14 Sep', '14 Sep, 09:10 AM', 'PDF + GeoTIFF'], ['Fleet health', 'Week 37', '14 Sep, 07:00 AM', 'PDF + XLSX'], ['Airspace and compliance', 'August', '01 Sep, 08:00 AM', 'PDF']].map(r => ({ n: `<b class="ink">${r[0]}</b>`, p: r[1], g: r[2], f: r[3], d: `<a data-act="${r[0]} downloaded (demo)">Download</a>` }))))}
      ${UI.card('Today so far (draft)', UI.steps([`${D.missionStats.today} missions today: ${D.missionStats.inProgress} in progress, ${D.missionStats.scheduled} scheduled, ${D.missionStats.completed} completed.`, `${D.home.dronesActive} drones active, ${D.home.inAir} in the air.`, `${D.alerts.length} active alerts: smoke at the refinery, a thermal anomaly on the dam, a stalled truck on NH-44.`, 'One mission paused (port sweep) and one failed (forest fire monitoring, link lost).', 'Mission success rate this month: 98%.']))}</div>` } } });

  VQ.screen('admin', { ws: 'ops', title: 'Administration', sub: 'Users, mission rules and the systems DroneOps IQ talks to.', views: { main: { render: () => { const t = VQ.state.ad || 'users';
    const body = { users: () => UI.table([{ k: 'r', label: 'Role' }, { k: 'n', label: 'Users', r: 1 }, { k: 'p', label: 'Can' }], [['Operations lead', 3, 'Approve and launch missions, change rules'], ['Mission planner', 8, 'Create and simulate missions'], ['Remote pilot', 14, 'Fly, pause, return, take manual control'], ['Visual observer (mobile)', 11, 'See live position, report hazards'], ['Data analyst', 6, 'Review detections, build reports'], ['Administrator', 2, 'Users, integrations, audit log']].map(r => ({ r: `<b class="ink">${r[0]}</b>`, n: r[1], p: r[2] }))) + `<div class="card-note mt">Signed in: ${D.user} (KK), Operations lead.</div>`,
      rules: () => UI.table([{ k: 'r', label: 'Rule' }, { k: 'v', label: 'Setting' }, { k: 'o', label: 'On' }], [['Land with battery reserve', '25% or more'], ['Maximum altitude', '120 m AGL'], ['Geofence buffer', '20 m (30 m at the refinery tank farm)'], ['Launch needs operator approval', 'Always'], ['Launch blocked outside the weather window', 'Always'], ['On link loss', 'Continue 60 s, then return'], ['Human review before alerts go to a client', 'Dam and refinery; not highway']].map(r => ({ r: `<b class="ink">${r[0]}</b>`, v: r[1], o: P.sw(1) }))),
      system: () => `<div class="grid g3" style="margin:0">${[['Airspace permissions (Digital Sky)', 'Connected', '08:40 AM'], ['Weather feed and site stations', 'Connected', '08:41 AM'], ['Drone docks and chargers', 'Connected', 'Live'], ['Video management system', 'Connected', 'Live'], ['Client control rooms (highway, refinery)', 'Connected', 'Live'], ['Cloud storage for mission data', 'Connected', '08:30 AM']].map(r => `<div class="chk ok">${I('link')}<div><b>${r[0]}</b><span>${r[1]} · last sync ${r[2]}</span></div></div>`).join('')}</div>` }[t]();
    return UI.card('Administration', UI.seg('ad', [['users', 'Users &amp; Roles'], ['rules', 'Mission Rules'], ['system', 'Integrations']], t) + `<div class="mt">${body}</div>`, { cls: 'mb', icon: 'gear' }); } } } });
})();
