/* Live Operations (dark) and Swarm Control */
(() => {
  const { UI, C, I } = VQ, D = VQ.ops, P = VQ.Plan;
  const live = () => D.missions.filter(m => m.status === 'In Progress' && m.uc);

  VQ.screen('live', { ws: 'ops', dark: true, title: 'Live Operations', sub: 'Missions in the air: position, video, telemetry and events.', views: { main: { render: () => { const M = live(), m = M.find(x => x.id === D.project().live) || M[0], U = D.usecases[m.uc], k = +(VQ.state.ld || 0), d = U.drones[k] || U.drones[0];
    const feed = { dam: ['th-eo.jpg', 'th-thermal.jpg', 'th-zoom.jpg'], highway: ['feed-highway.jpg', 'hw-cam-stalled-truck.jpg', 'hw-cam-corridor-1.jpg'], refinery: ['ref-feed-unit3.jpg', 'ref-thermal-column.jpg', 'ref-cam-column.jpg'] }[m.uc];
    VQ.store.set('ctl', { uc: m.uc, k });
    return UI.kpis([{ icon: 'drone', bg: 'bg-info', value: D.home.inAir, label: 'Drones in the Air', delta: { text: `${D.home.onGround} on the ground, ready` } }, { icon: 'route', bg: 'bg-violet', value: D.missionStats.inProgress, label: 'Missions in Progress' }, { icon: 'alert', bg: 'bg-crit', value: D.alerts.length, label: 'Active Alerts', go: 'alerts' }, { icon: 'wifi', bg: 'bg-good', value: '100%', label: 'Links Healthy', delta: { text: 'No drone on failover' } }], 'g4 compact')
    + `<div class="grid g-2-1"><div class="card"><div class="card-h"><h3>${m.name}</h3><div class="right">${UI.pill(D.project().name, 'info')}${UI.pill(m.pct + '% complete', 'good')}</div></div>${VQ.MMap.render({ uc: m.uc, h: 430, at: [m.pct / 100, m.pct / 100 * .95, m.pct / 100 * .9], layers: { area: 1, path: 1, sectors: 1, nfz: 1, drones: 1 }, showLayers: [['drones', 'Drones'], ['sectors', 'Swarm sectors'], ['path', 'Flight path'], ['nfz', 'Geo-fence'], ['comms', 'Link coverage'], ['elz', 'Landing zones']] })}</div>
      <div class="col">${UI.card('Live Drone Feed', UI.seg('ld', U.drones.map((x, i) => [String(i), x.name]), String(k)) + `<div class="row mt">${UI.btn('Take Control of ' + d.id, { sm: 1, primary: 1, icon: 'gauge', go: 'control' })}<span class="small t2">Pilot view, flight modes and the emergency deck</span></div><div class="mt">${UI.cam({ img: feed[k] || feed[0], cls: /thermal/i.test(d.p1) && !/thermal/.test(feed[k]) ? 'thermal' : '', label: `${d.id} · ${d.p1}`, time: '08:42:17 AM', foot: d.sector, extra: `<div class="hud">ALT ${U.alt} m · SPD ${U.speed} m/s · BATT ${d.batt - 30}%<br>${U.lat.toFixed(4)} N, ${U.lon.toFixed(4)} E</div>`, boxes: m.alerts && k === (m.uc === 'dam' ? 2 : 0) ? [{ x: 36, y: 30, w: 28, h: 40, label: D.alerts.find(a => a.mission === m.id).title, tone: 'crit' }] : [] })}</div>`)}
        ${UI.card('Telemetry', `<div class="list">${U.drones.map(x => `<div class="li" style="align-items:center"><div class="li-ic tone-info">${I('drone')}</div><div class="li-body"><div class="li-title"><a data-go="drone/${x.id}">${x.name} · ${x.id}</a></div><div class="li-sub">${x.role} · ${U.alt} m · link strong</div></div><span class="batt"><i style="--p:${x.batt - 30}%;--c:var(--good)"></i>${x.batt - 30}%</span></div>`).join('')}</div>`)}</div></div>
    <div class="grid g3">${UI.card('Events', UI.vtimeline([{ t: '08:37', text: 'Alert raised and sent to the Command Center', tone: 'crit' }, { t: '08:22', text: 'Waypoint block 4 completed', tone: 'good' }, { t: '08:18', text: 'Swarm re-tasked one drone for a second pass', tone: 'ai' }, { t: '08:05', text: 'All drones entered the mission area', tone: 'good' }]))}
      ${UI.card('Operator controls', UI.quick([{ icon: 'gauge', label: 'Take Control', go: 'control' }, { icon: 'crosshair', label: 'Remote Pilot', go: 'pilot' }, { icon: 'x', label: 'Pause Mission' }, { icon: 'home', label: 'Return to Home' }, { icon: 'crosshair', label: 'Hold Position' }, { icon: 'clip', label: 'Record Clip' }, { icon: 'mega', label: 'Notify Site Team' }, { icon: 'net', label: 'Swarm Control', go: 'swarm' }]))}
      ${UI.card('Alerts on this mission', m.alerts ? UI.list(D.alerts.filter(a => a.mission === m.id).map(a => ({ thumb: a.img, title: a.title, titleTone: 'crit', sub: a.where, sub2: a.text, go: `alert/${a.id}` }))) : '<div class="card-note">No alerts on this mission.</div>')}</div>`; } } } });

  VQ.screen('swarm', { ws: 'ops', title: 'Swarm Control', sub: 'One operator, many drones: formation, roles and behaviour, live.', views: { main: { render: () => { const U = D.usecases.dam, f = VQ.state.sf || 'grid', n = 6, R = 58, L = VQ.store.get('swarm', { alt: 120, spd: 12, sp: 50, sep: 10 }), k = L.sp / 50;
    window.VQswarm = (key, v) => { L[key] = +v; VQ.store.set('swarm', L); VQ.render(true); };
    const pos = { grid: [[-70, -30], [0, -30], [70, -30], [-70, 30], [0, 30], [70, 30]], v: [[0, -50], [-40, -15], [40, -15], [-80, 20], [80, 20], [0, 30]], line: [[-100, 0], [-60, 0], [-20, 0], [20, 0], [60, 0], [100, 0]], circle: Array.from({ length: 6 }, (_, i) => [Math.cos(i / 6 * 2 * Math.PI) * R * 1.3, Math.sin(i / 6 * 2 * Math.PI) * R]) }[f].map(p => [p[0] * k, p[1] * k]);
    return UI.kpis([{ icon: 'net', bg: 'bg-violet', value: 3, label: 'Swarms Active', delta: { text: 'Alpha · Bravo · Delta' } }, { icon: 'drone', bg: 'bg-info', value: 8, label: 'Drones in Swarms' }, { icon: 'wifi', bg: 'bg-good', value: '38 ms', label: 'Mesh Latency' }, { icon: 'shieldcheck', bg: L.sp < 30 ? 'bg-crit' : 'bg-good', value: Math.round(L.sp * .76) + ' m', label: 'Closest Separation', delta: { text: L.sp < 30 ? 'Below the 15 m limit margin' : 'Hard limit 15 m' } }], 'g4 compact')
    + `<div class="grid g-2-1"><div class="col">${UI.card('Swarm Alpha · Formation', `${UI.seg('sf', [['grid', 'Area grid'], ['v', 'V formation'], ['line', 'Line abreast'], ['circle', 'Orbit']], f)}<svg viewBox="-160 -90 320 180" style="width:100%;height:290px;margin-top:10px;border:1px dashed var(--axis);border-radius:10px;background:var(--blue-50)"><ellipse rx="140" ry="76" fill="none" stroke="var(--axis)" stroke-dasharray="5 5"/>${pos.map((p, i) => pos.slice(i + 1).filter(q => Math.hypot(q[0] - p[0], q[1] - p[1]) < 95).map(q => `<line x1="${p[0]}" y1="${p[1]}" x2="${q[0]}" y2="${q[1]}" stroke="var(--s1)" opacity=".35"/>`).join('')).join('')}${pos.map((p, i) => `<g transform="translate(${p[0]},${p[1]})"><circle r="13" fill="${i === 0 ? '#1565d8' : i === 5 ? '#6a4fd0' : '#12a150'}"/>${VQ.iconG('drone', 0, 0, 15, '#fff', 2)}<text y="26" text-anchor="middle" style="font-size:8.5px;fill:var(--text-2);font-family:Inter">${i === 0 ? 'Lead' : i === 5 ? 'Relay' : 'Survey ' + i}</text></g>`).join('')}</svg><div class="card-note mt">Lines show the drone-to-drone mesh. Blue is the lead, violet the relay. Spacing ${L.sp} m, altitude ${L.alt} m, ${L.spd} m/s: the swarm covers a strip ${L.sp * 5} m wide at ${(L.spd * 3.6).toFixed(0)} km/h.</div>`, { right: `<span class="small">${n} drones · area scan</span>` })}
        ${UI.card('Roles', UI.table([{ k: 'd', label: 'Drone' }, { k: 'r', label: 'Role' }, { k: 't', label: 'Task' }, { k: 'b', label: 'Battery' }, { k: 'l', label: 'Mesh link' }], ['DR-001', 'DR-003', 'DR-007', 'DR-017', 'DR-020', 'DR-014'].map((d, i) => ({ d: `<b class="ink">${d}</b>`, r: i === 0 ? 'Lead' : i === 5 ? 'Relay' : i % 2 ? 'Thermal' : 'Survey', t: i === 5 ? `Holds at ${L.alt + 30} m` : `Sector ${'ABCDE'[i]} · ${L.alt + i * L.sep} m`, b: `<span class="batt"><i style="--p:${88 - i * 5}%;--c:var(--good)"></i>${88 - i * 5}%</span>`, l: UI.pill(i === 4 ? 'Fair' : 'Strong', i === 4 ? 'warn' : 'good') }))))}</div>
      <div class="col">${UI.card('Live parameters', `<div class="col" style="gap:12px"><div><div class="row between small t2 mb"><span>Altitude</span><b class="ink">${L.alt} m</b></div><input type="range" min="30" max="120" step="5" value="${L.alt}" style="width:100%;accent-color:var(--blue)" oninput="this.previousElementSibling.querySelector('b').textContent=this.value+' m'" onchange="VQswarm('alt',this.value)"></div><div><div class="row between small t2 mb"><span>Speed</span><b class="ink">${L.spd} m/s</b></div><input type="range" min="2" max="18" step="1" value="${L.spd}" style="width:100%;accent-color:var(--blue)" oninput="this.previousElementSibling.querySelector('b').textContent=this.value+' m/s'" onchange="VQswarm('spd',this.value)"></div><div><div class="row between small t2 mb"><span>Spacing</span><b class="ink">${L.sp} m</b></div><input type="range" min="20" max="120" step="5" value="${L.sp}" style="width:100%;accent-color:var(--blue)" oninput="this.previousElementSibling.querySelector('b').textContent=this.value+' m'" onchange="VQswarm('sp',this.value)"></div><div><div class="row between small t2 mb"><span>Altitude separation</span><b class="ink">${L.sep} m</b></div><input type="range" min="5" max="30" step="5" value="${L.sep}" style="width:100%;accent-color:var(--blue)" oninput="this.previousElementSibling.querySelector('b').textContent=this.value+' m'" onchange="VQswarm('sep',this.value)"></div></div><div class="card-note mt">Drag a slider: the formation, the roles table and the separation figure update. Apply sends it to the drones.</div><div class="row mt">${UI.btn('Apply to Swarm', { primary: 1, toast: `Sent to 6 drones: ${L.alt} m, ${L.spd} m/s, spacing ${L.sp} m`, done: 'Applied' })}${UI.btn('Launch Swarm', { toast: 'Swarm Alpha launch sequence started' })}</div>`)}
        ${UI.card('Swarm behaviour', `<div class="row between"><span class="t2">Re-split the task if a drone drops out</span>${P.sw(1)}</div><div class="row between mt"><span class="t2">Promote a new lead automatically</span>${P.sw(1)}</div><div class="row between mt"><span class="t2">Send the nearest drone to verify an alert</span>${P.sw(1)}</div><div class="row between mt"><span class="t2">Hold formation in a link shadow</span>${P.sw(0)}</div><div class="insight mt" style="margin-bottom:0"><span style="color:var(--violet)">${I('sparkles')}</span><div><b>08:18 AM: the swarm decided</b><p>DR-007 saw a thermal anomaly on the dam toe. The swarm gave its remaining lines to DR-003 and sent DR-007 back for a second pass. No operator input.</p></div></div>`)}
        ${UI.card('Active swarms', UI.list([{ icon: 'net', tone: 'info', title: 'Swarm Alpha · North Ridge Dam', sub: '3 drones · 65% complete', go: 'live' }, { icon: 'net', tone: 'info', title: 'Swarm Bravo · NH-44 Corridor', sub: '2 drones + relay · 40% complete', go: 'live' }, { icon: 'net', tone: 'info', title: 'Swarm Delta · Flood assessment, Kerala', sub: '3 drones · 40% complete', go: 'missions' }]) + `<div class="row mt">${UI.btn('Configure a swarm for a new mission', { sm: 1, go: 'plan/swarm' })}</div>`)}</div></div>`; } } } });
})();
