/* Remote Pilot · a pilot connects a joystick and flies one drone by hand.
   If a real gamepad is plugged in (Gamepad API) its sticks drive the screen; otherwise a demo pattern moves them. */
(() => {
  const { UI, I } = VQ, D = VQ.ops;
  const AX = [['LX', 'Left stick X', 'Yaw'], ['LY', 'Left stick Y', 'Throttle'], ['RX', 'Right stick X', 'Roll'], ['RY', 'Right stick Y', 'Pitch']];
  const BT = [['A', 'Take off / Land'], ['B', 'Return to Launch'], ['X', 'Capture photo'], ['Y', 'Start / stop recording'], ['LB', 'Gimbal down'], ['RB', 'Gimbal up'], ['LT', 'Slow mode'], ['RT', 'Sport mode'], ['Start', 'Arm / Disarm'], ['Back', 'Emergency brake']];
  const pad = () => { try { const g = navigator.getGamepads ? [...navigator.getGamepads()].find(x => x) : null; return g || null; } catch (e) { return null; } };

  VQ.screen('pilot', { ws: 'ops', dark: true, title: 'Remote Pilot', sub: 'Connect a joystick and fly a drone by hand, with every safety rule still in force.',
    headRight: () => `<div class="seg">${D.uc().drones.map((d, i) => `<button class="${i === +(VQ.store.get('pk', 0)) ? 'on' : ''}" onclick="VQ.store.set('pk',${i});VQ.render(true)">${d.id}</button>`).join('')}</div>`,
    views: { main: { render: () => { const U = D.uc(), k = +(VQ.store.get('pk', 0)), d = U.drones[k] || U.drones[0], img = { dam: 'th-eo.jpg', highway: 'feed-highway.jpg', refinery: 'ref-feed-unit3.jpg' }[U.key], real = pad();
      const stick = (id, lab) => `<div style="text-align:center"><svg viewBox="0 0 120 120" style="width:118px;height:118px"><circle cx="60" cy="60" r="54" fill="#122c59" stroke="#35558c" stroke-width="2"/><circle cx="60" cy="60" r="36" fill="none" stroke="#35558c" stroke-dasharray="4 4"/><path d="M60,6 V114 M6,60 H114" stroke="#35558c"/><circle id="${id}" cx="60" cy="60" r="17" fill="#2f8bff" stroke="#fff" stroke-width="3"/></svg><div class="small t2">${lab}</div></div>`;
      const sched = () => { clearInterval(VQ._joy); const t0 = Date.now(), q = id => document.getElementById(id); let log = [], armed = true;
        VQ._joy = setInterval(() => { if (!q('js-l')) return clearInterval(VQ._joy); const g = pad(), t = (Date.now() - t0) / 1000;
          let a = g ? [g.axes[0] || 0, g.axes[1] || 0, g.axes[2] || 0, g.axes[3] || 0] : [Math.sin(t * .9) * .55, -Math.abs(Math.sin(t * .5)) * .5 + .1, Math.sin(t * .7 + 1) * .6, Math.cos(t * .6) * .45];
          a = a.map(v => Math.abs(v) < .06 ? 0 : v); const btn = g ? g.buttons.map(b => b.pressed) : BT.map((_, i) => Math.floor(t / 4) % 10 === i && t % 4 < 1.2);
          q('js-l').setAttribute('cx', 60 + a[0] * 36); q('js-l').setAttribute('cy', 60 + a[1] * 36); q('js-r').setAttribute('cx', 60 + a[2] * 36); q('js-r').setAttribute('cy', 60 + a[3] * 36);
          a.forEach((v, i) => { const b = q('ax' + i); if (b) { b.style.width = Math.abs(v) * 50 + '%'; b.style.left = v < 0 ? 50 - Math.abs(v) * 50 + '%' : '50%'; q('axv' + i).textContent = (v * 100).toFixed(0) + '%'; } });
          btn.forEach((p, i) => { const e = q('bt' + i); if (e) e.classList.toggle('on', !!p); });
          const cam = q('js-cam'); if (cam) cam.style.transform = `rotate(${(-a[2] * 6).toFixed(1)}deg) translateY(${(a[3] * 10).toFixed(1)}px) scale(1.06)`;
          const roll = -a[2] * 25, pitch = -a[3] * 15, yaw = (t * 3 + a[0] * 40) % 360; const h = q('js-hor'); if (h) h.setAttribute('transform', `rotate(${roll} 60 60) translate(0 ${pitch * 1.5})`); const cp = q('js-cmp'); if (cp) cp.setAttribute('transform', `rotate(${-yaw} 150 60)`);
          const alt = U.alt + Math.round(-a[1] * 12), spd = Math.abs(a[3]) * 12 + Math.abs(a[2]) * 6; ['js-alt', 'js-spd', 'js-yaw', 'js-vsi'].forEach((id, i) => { const e = q(id); if (e) e.textContent = [alt + ' m', spd.toFixed(1) + ' m/s', Math.round((yaw + 360) % 360) + '°', (-a[1] * 2.5).toFixed(1) + ' m/s'][i]; });
          const dr = q('js-dr'); if (dr) { const x = 500 + Math.sin(t * .35) * 180 + a[2] * 40, y = 280 + Math.cos(t * .3) * 90 + a[3] * 30; dr.setAttribute('transform', `translate(${x.toFixed(0)},${y.toFixed(0)}) rotate(${yaw})`); const tr = q('js-trail'); if (tr) { const pts = (tr.getAttribute('points') || '').split(' ').filter(Boolean); pts.push(`${x.toFixed(0)},${y.toFixed(0)}`); tr.setAttribute('points', pts.slice(-160).join(' ')); } }
          const active = AX.map((x, i) => Math.abs(a[i]) > .35 ? `${x[2]} ${a[i] > 0 ? (i % 2 ? 'down' : 'right') : (i % 2 ? 'up' : 'left')} ${(Math.abs(a[i]) * 100).toFixed(0)}%` : null).filter(Boolean); const bp = btn.findIndex(Boolean);
          const line = bp >= 0 && BT[bp] ? `${BT[bp][0]}: ${BT[bp][1]}` : active[0]; if (line && line !== log[0]) { log.unshift(line); log = log.slice(0, 6); const lg = q('js-log'); if (lg) lg.innerHTML = log.map((l, i) => `<div class="ev ${i ? '' : 'good'}"><i></i><time>${new Date().toTimeString().slice(0, 8)}</time>${l}</div>`).join(''); }
          const src = q('js-src'); if (src) src.textContent = g ? `${g.id.slice(0, 40)} · live input` : 'Demo joystick · simulated input'; }, 70); };
      VQ.mount(sched);
      return `<div class="grid g3 kpis compact">${[[real ? 'checkc' : 'gauge', real ? 'Joystick connected' : 'Demo joystick', real ? real.id.slice(0, 34) : 'Plug in any USB or Bluetooth gamepad to fly with it', real ? 'good' : 'info'], ['drone', `${d.id} · ${d.model}`, `${d.role} · link strong · battery ${d.batt - 30}%`, 'good'], ['shield', 'Safety rules stay on', 'Geofence, 120 m ceiling and 25% reserve still apply to manual flight', 'good']].map(k => `<div class="card kpi"><div class="kpi-ic bg-${k[3]}">${I(k[0])}</div><div><div class="kpi-val" style="font-size:15px">${k[1]}</div><div class="kpi-lbl">${k[2]}</div></div></div>`).join('')}</div>
      <div class="grid" style="grid-template-columns:minmax(0,1.1fr) minmax(0,1.6fr) minmax(0,1fr)">
        <div class="col">${UI.card('Controller', `<div class="row" style="justify-content:space-around">${stick('js-l', 'Throttle / Yaw')}${stick('js-r', 'Pitch / Roll')}</div><div class="row wrap mt" style="gap:6px;justify-content:center">${BT.map((b, i) => `<span id="bt${i}" class="pill gray js-btn">${b[0]}</span>`).join('')}</div><div class="card-note mt" id="js-src">Demo joystick · simulated input</div>`, { icon: 'gauge' })}
          ${UI.card('Axes', AX.map((x, i) => `<div class="row" style="margin-bottom:7px;gap:8px"><span class="small t2" style="width:74px">${x[0]} · ${x[2]}</span><div style="position:relative;flex:1;height:10px;border-radius:5px;background:var(--blue-100)"><i id="ax${i}" style="position:absolute;top:0;bottom:0;left:50%;width:0;background:var(--blue);border-radius:5px"></i><i style="position:absolute;left:50%;top:-2px;bottom:-2px;width:1px;background:var(--axis)"></i></div><b class="ink small" id="axv${i}" style="width:38px;text-align:right">0%</b></div>`).join('') + '<div class="card-note">Dead zone 6%. Expo 30%. Rates: normal.</div>')}</div>
        <div class="col"><div class="card flush"><div style="position:relative;aspect-ratio:16/9;overflow:hidden;background:#000"><img id="js-cam" src="assets/img/${img}" alt="" style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover;transition:transform .07s linear;transform:scale(1.06)"><svg viewBox="0 0 400 225" style="position:absolute;inset:0;width:100%;height:100%"><g stroke="#8fff9a" fill="none" stroke-width="1.2" opacity=".9"><circle cx="200" cy="112" r="20"/><path d="M200,82 V96 M200,128 V142 M170,112 H184 M216,112 H230"/><path d="M40,40 H70 M40,40 V70 M360,40 H330 M360,40 V70 M40,185 H70 M40,185 V155 M360,185 H330 M360,185 V155"/></g><text x="12" y="20" style="font:700 11px ui-monospace,Menlo,monospace;fill:#8fff9a">FPV · ${d.id} · MANUAL</text><text x="388" y="20" text-anchor="end" style="font:700 11px ui-monospace,Menlo,monospace;fill:#ff6a61">● REC</text></svg>
            <div class="hud" style="left:12px;bottom:12px">ALT <span id="js-alt">${U.alt} m</span> · GS <span id="js-spd">0.0 m/s</span> · VSI <span id="js-vsi">0.0 m/s</span> · HDG <span id="js-yaw">0°</span><br>${U.lat.toFixed(4)} N, ${U.lon.toFixed(4)} E · RTK · LINK -62 dBm</div></div>
          <div class="simbar" style="border-radius:0 0 8px 8px;flex-wrap:wrap"><span class="pill solid-good">MANUAL · Pos Hold</span><span class="grow small" style="min-width:200px">Release the sticks and the drone holds position. Fence, ceiling and reserve rules still apply.</span>${UI.btn('Hand back to Auto', { sm: 1, toast: d.id + ' resumed its mission plan', done: 'Auto' })}</div></div>
          ${UI.card('Position', `<div class="mmap" style="height:190px;background:#1d2b3f"><svg viewBox="0 0 1000 560" preserveAspectRatio="xMidYMid slice"><rect width="1000" height="560" fill="#1d2b3f"/>${Array.from({ length: 10 }, (_, i) => `<line x1="${i * 100}" y1="0" x2="${i * 100}" y2="560" stroke="#2a3d5a"/><line x1="0" y1="${i * 60}" x2="1000" y2="${i * 60}" stroke="#2a3d5a"/>`).join('')}<polygon points="250,120 760,90 820,330 640,470 300,380" fill="#3b9bff" opacity=".12" stroke="#6fb6ff" stroke-dasharray="6 5"/><polygon points="700,400 790,385 805,450 715,465" fill="#ff4d45" opacity=".3" stroke="#ff4d45"/><text x="700" y="392" style="font-size:11px;fill:#ffd1ce;font-weight:700">NFZ</text><circle cx="180" cy="450" r="14" fill="#12a150" stroke="#fff" stroke-width="2"/><text x="180" y="455" text-anchor="middle" style="font-size:13px;fill:#fff;font-weight:800">H</text><polyline id="js-trail" points="" fill="none" stroke="#2f8bff" stroke-width="2" opacity=".8"/><g id="js-dr" transform="translate(500,280)"><circle r="16" fill="#2f8bff" opacity=".3"/><circle r="10" fill="#2f8bff" stroke="#fff" stroke-width="2"/><path d="M0,-16 L5,-6 L-5,-6Z" fill="#fff"/></g></svg><div class="note">Manual flight inside the mission fence</div></div>`)}</div>
        <div class="col">${UI.card('Flight HUD', `<svg viewBox="0 0 200 120" style="width:100%;height:140px;background:#0a1630;border-radius:8px"><defs><clipPath id="jai"><circle cx="60" cy="60" r="46"/></clipPath></defs><g clip-path="url(#jai)"><g id="js-hor"><rect x="-40" y="-60" width="200" height="120" fill="#2f7fd6"/><rect x="-40" y="60" width="200" height="120" fill="#8a5a2b"/><line x1="-40" y1="60" x2="160" y2="60" stroke="#fff" stroke-width="1.5"/></g></g><circle cx="60" cy="60" r="46" fill="none" stroke="#8ea3c7" stroke-width="2"/><path d="M38,60 H52 L60,66 L68,60 H82" fill="none" stroke="#ffd21f" stroke-width="2.5"/><circle cx="150" cy="60" r="40" fill="#0e2248" stroke="#8ea3c7" stroke-width="2"/><g id="js-cmp">${['N', 'E', 'S', 'W'].map((c, i) => `<text x="${150 + Math.cos((i * 90 - 90) * Math.PI / 180) * 30}" y="${64 + Math.sin((i * 90 - 90) * Math.PI / 180) * 30}" text-anchor="middle" style="font:700 10px Inter;fill:${c === 'N' ? '#ff6a61' : '#cfe0ff'}">${c}</text>`).join('')}</g><path d="M150,32 l6,34 h-12z" fill="#ffd21f"/></svg>`, { icon: 'gauge' })}
          ${UI.card('Button map', UI.table([{ k: 'b', label: 'Button' }, { k: 'a', label: 'Action' }], BT.map(b => ({ b: `<b class="ink">${b[0]}</b>`, a: b[1] }))) + `<div class="row mt">${UI.btn('Calibrate', { sm: 1, toast: 'Move each stick to its limits, then centre. Calibration saved.' })}${UI.btn('Remap', { sm: 1, ghost: 1, toast: 'Press the button you want to assign' })}</div>`)}
          ${UI.card('Command log', `<div class="vtl" id="js-log"><div class="ev"><i></i><time>08:42:17</time>Manual control taken from Auto</div></div>`, { icon: 'clock' })}</div></div>`; } } } });
})();
