/* =========================================================
   Mission Planning · top tabs Plan | Payload | Safety | Advanced, each with sub-tabs.
   This file: shared navigation + Plan (area, swarm, schedule, coverage) and Payload (payload, ai).
   ========================================================= */
VQ.Plan = (() => {
  const { UI, C, I } = VQ, D = VQ.ops;
  const NAV = [['Plan', [['area', 'Area &amp; Flight'], ['swarm', 'Swarm Configuration'], ['schedule', 'Scheduling'], ['coverage', 'Coverage &amp; Capture']]], ['Payload', [['payload', 'Payload Configuration'], ['ai', 'AI Detection']]],
    ['Safety', [['geofence', 'Geofencing &amp; Safety'], ['weather', 'Weather Constraints'], ['comms', 'Communications']]], ['Advanced', [['flight', 'Flight Parameters'], ['simulate', 'Mission Simulation'], ['readiness', 'Mission Readiness'], ['launch', 'Summary &amp; Launch']]]];
  /* the order the planner walks through */
  const SEQ = ['area', 'payload', 'swarm', 'geofence', 'weather', 'schedule', 'flight', 'coverage', 'ai', 'comms', 'simulate', 'readiness', 'launch'];
  const label = v => NAV.flatMap(n => n[1]).find(x => x[0] === v)[1];
  const SUB = { area: 'Plan a single drone or a swarm mission. Define area, capture plan and automated flight parameters.', payload: 'Configure payloads and sensors for your mission. Match the right data to the right outcome.', swarm: 'Assign drones and roles, choose a formation, and decide what happens if a drone drops out.', geofence: 'No-fly zones, clearances, safe corridors and where each drone goes if something fails.',
    weather: 'Limits, the forecast along the mission timeline, and the window in which this mission can fly.', schedule: 'When it flies, how often, and what it collides with.', flight: 'Speed by segment, altitude profile, waypoint behaviour and what the drone does when the link drops.', coverage: 'What the mission will actually capture, and how sure we are.',
    ai: 'What the mission looks for, how sure it must be, and what counts as an alert.', comms: 'Every link the mission depends on, where it gets weak, and the fallback.', simulate: 'Fly the whole mission before launch.', readiness: 'Final pre-flight check. Exceptions first.', launch: 'Everything about this mission on one page.' };

  const fld = (v, unit) => `<div class="fld"><span>${v}</span>${unit ? `<em>${unit}</em>` : I('chevd')}</div>`;
  /* editable fields: type or pick, and the plan recomputes */
  const inp = (f, v, unit, o) => { o = o || {}; return `<div class="fld edit"><input type="${o.num ? 'number' : 'text'}" value="${VQ.esc(v)}" ${o.step ? `step="${o.step}"` : ''} ${o.min != null ? `min="${o.min}"` : ''} ${o.max != null ? `max="${o.max}"` : ''} onchange="VQ.ops.edit('${f}', this.value)" onkeydown="if(event.key==='Enter')this.blur()" aria-label="${f}">${unit ? `<em>${unit}</em>` : ''}</div>`; };
  const pick = (f, v, list) => `<div class="fld edit"><select onchange="VQ.ops.edit('${f}', this.value)" aria-label="${f}">${list.map(x => `<option ${x === v ? 'selected' : ''}>${x}</option>`).join('')}</select>${I('chevd')}</div>`;
  const frm = rows => `<div class="frm ${rows.length < 3 ? 'tight' : ''}">${rows.map(r => `<label>${r[0]}</label>${r[2] === 'raw' ? r[1] : fld(r[1], r[2])}`).join('')}</div>`;
  const sw = on => `<span class="sw ${on ? 'on' : ''}" onclick="this.classList.toggle('on')"></span>`;
  const sld = (pct, txt) => `<div class="row" style="gap:10px"><div class="sld"><i style="width:${pct}%"></i><b style="left:${pct}%"></b></div><b class="ink small" style="min-width:64px;text-align:right">${txt}</b></div>`;
  const opts = (list, cur, key) => `<div class="opt-grid">${list.map(o => `<button class="opt ${o[0] === cur ? 'on' : ''}" ${key ? `data-set="${key}=${o[0]}"` : `data-act="${o[1]} selected"`}>${I(o[2])}<span>${o[1]}</span></button>`).join('')}</div>`;
  const chk = (tone, title, text) => `<div class="chk ${tone}">${I(tone === 'ok' ? 'checkc' : tone === 'warn' ? 'alert' : 'octagon')}<div><b>${title}</b><span>${text}</span></div></div>`;
  const droneRow = (d, right) => `<div class="li" style="align-items:center"><img src="assets/img/drone-small.jpg" alt="" style="width:54px;height:30px;object-fit:contain;flex:none"><div class="li-body"><div class="li-title">${d.name} <a data-go="drone/${d.id}" class="small">${d.id}</a></div><div class="li-sub">${d.model}</div></div>${right}</div>`;

  function head({ vid }) { const U = D.uc(), top = NAV.findIndex(n => n[1].some(x => x[0] === vid)), step = SEQ.indexOf(vid);
    return `<div class="page-head"><div><h1>Mission Planning</h1><div class="sub">${SUB[vid]}</div></div><div class="head-right">
        <div class="mission-chip"><div><span class="small t2">Project</span><b>${D.project().name} · ${D.project().sector}</b></div></div>
        <div class="mission-chip"><div><b>Mission: ${U.id}</b>${U.name}</div>${UI.pill('Draft', 'good')}<div class="t2">Last saved<br><b class="ink" style="font-size:12px">Today, 08:40 AM</b></div></div></div></div>
      <div class="ptabs">${NAV.map((n, i) => `<button class="${i === top ? 'on' : ''}" data-go="plan/${n[1][0][0]}">${n[0]}</button>`).join('')}</div>
      <div class="psub">${NAV[top][1].map(x => { const k = SEQ.indexOf(x[0]); return `<button class="${x[0] === vid ? 'on' : k < step ? 'done' : ''}" data-go="plan/${x[0]}"><span class="n">${k < step ? '✓' : k + 1}</span>${x[1]}</button>`; }).join('')}</div>`; }
  function foot(vid) { const k = SEQ.indexOf(vid), prev = SEQ[k - 1], next = SEQ[k + 1];
    return `<div class="pnext"><div class="t2">Step <b class="ink">${k + 1} of ${SEQ.length}</b> · ${label(vid)}</div><div class="row">${prev ? UI.btn('Back: ' + label(prev), { ghost: 1, icon: 'arrowl', go: 'plan/' + prev }) : ''}${UI.btn('Save Mission', { icon: 'check', toast: 'Mission saved as draft', done: 'Saved' })}${next ? UI.btn('Next: ' + label(next), { primary: 1, go: 'plan/' + next }) : ''}</div></div>`; }
  const view = (vid, fn) => ({ render: ctx => fn(D.uc(), ctx) + foot(vid) });

  const views = {};
  /* ---------- Plan · Area & Flight (mockup 02) ---------- */
  views.area = view('area', U => { const prof = VQ.series(21, (U.maxTerrain + U.minTerrain) / 2, 20, 4, (i, n) => Math.sin(i / n * Math.PI * 1.6) * (U.maxTerrain - U.minTerrain) / 2.4), km = prof.map((_, i) => (i / 10).toFixed(1));
    return `<div class="grid" style="grid-template-columns:minmax(0,1.25fr) minmax(0,2.5fr) minmax(0,1.5fr)">
      ${UI.card(`<span class="fld edit" style="padding:0;border:0;background:none;display:block;width:100%"><input value="${VQ.esc(U.name)}" onchange="VQ.ops.edit('name', this.value)" onkeydown="if(event.key==='Enter')this.blur()" style="font-size:15px;font-weight:700" aria-label="Mission name"></span>`, frm([['Mission Type', pick('type', U.type, ['Inspection', 'Patrol', 'Survey', 'Mapping', 'Security', 'Emergency Response', 'Delivery']), 'raw'], ['Use Case', pick('usecase', U.usecase.replace('&amp;', '&'), ['Infrastructure Inspection', 'Highway Corridor Monitoring', 'Oil & Gas Asset Inspection', 'Canal / Water Patrol', 'Solar Farm Survey', 'Perimeter Security', 'Flood Assessment', 'Urban Mapping', 'Forest Fire Monitoring']), 'raw'], ['Location', inp('location', U.location), 'raw'], [U.areaLabel + ' (km²)', inp('areaKm', U.areaKm, 'km²', { num: 1, step: .1, min: .1, max: 50 }), 'raw'], ['Drones', `${U.drones.length} (Swarm) · <a data-go="plan/swarm">edit</a>`, ' '], ['Camera Payload', `${[...new Set(U.drones.map(d => d.p1.replace(' Camera', '')))].slice(0, 3).join(' + ')} · <a data-go="plan/payload">edit</a>`, ' '], ['Estimated Time', `<b class="ink">${U.minutes} min</b> <em class="small t2">computed</em>`, ' '], ['Created By', D.user, ' '], ['Last Saved', U.edited ? 'Unsaved edits' : 'Today, 08:40 AM', ' ']]) + `<hr class="sep"><div class="small t2"><b class="ink">Objective.</b> <span class="fld edit" style="padding:0;border:0;background:none;display:block"><textarea rows="3" onchange="VQ.ops.edit('objective', this.value)" aria-label="Objective">${VQ.esc(U.objective)}</textarea></span></div>` + (U.edited ? `<div class="row mt"><a onclick="VQ.ops.resetEdits()">Reset to defaults</a><span class="small t2">· ${U.edited} field${U.edited > 1 ? 's' : ''} changed; time, images, waypoints and data are recomputed</span></div>` : ''))}
      <div class="card flush">${VQ.MMap.render({ uc: U.key, h: 470, center: U.key === 'dam' ? [560, 280] : U.key === 'highway' ? [500, 400] : [640, 470], layers: { area: 1, path: 1, waypoints: 1, nfz: 1, drones: 1 }, showLayers: [['area', 'Coverage Area'], ['path', 'Flight Path'], ['waypoints', 'Waypoints'], ['nfz', 'No-Fly Zones'], ['obst', 'Obstacles'], ['weather', 'Weather'], ['comms', 'Comms Coverage'], ['drones', 'Drones']] })}</div>
      <div class="col">${UI.card('Area Definition', opts([['draw', 'Draw Area', 'grid'], ['imp', 'Import', 'download'], ['asset', 'Select Asset', 'mappin'], ['corr', 'Corridor', 'road'], ['poi', 'Point of Interest', 'crosshair']], U.key === 'dam' ? 'draw' : U.key === 'highway' ? 'corr' : 'poi') + `<div class="grid g2 mt" style="margin-bottom:0">${frm([[U.areaLabel, inp('areaKm', U.areaKm, 'km²', { num: 1, step: .1, min: .1, max: 50 }), 'raw']])}${frm([['Perimeter', U.perimeter, ' ']])}</div>`)}
        ${UI.card('Flight Pattern', `<div class="opt-grid">${[['Grid', 'grid'], ['Orbits', 'refresh'], ['Corridor', 'road'], ['Custom', 'route']].map(o => `<button class="opt ${o[0] === U.pattern ? 'on' : ''}" onclick="VQ.ops.edit('pattern','${o[0]}')">${I(o[1])}<span>${o[0]}</span></button>`).join('')}</div><div class="grid g2 mt" style="margin-bottom:0">${frm([['Overlap (Front)', inp('overlapF', U.overlapF, '%', { num: 1, min: 30, max: 95 }), 'raw'], ['Flight Altitude', inp('alt', U.alt, 'm', { num: 1, min: 20, max: 120 }), 'raw']])}${frm([['Overlap (Side)', inp('overlapS', U.overlapS, '%', { num: 1, min: 30, max: 95 }), 'raw'], ['GSD', `<b class="ink">${U.gsd}</b> <em class="small t2">cm/px, from altitude</em>`, ' ']])}</div><div class="row between mt"><span class="t2">Preview Coverage</span>${sw(1)}</div>`)}
        ${UI.card('Mission Settings', `<div class="grid g2" style="margin-bottom:8px">${frm([['Speed', inp('speed', U.speed, 'm/s', { num: 1, min: 1, max: 20 }), 'raw']])}${frm([['Capture Interval', inp('interval', U.interval, 'sec', { num: 1, min: 1, max: 10 }), 'raw']])}</div>${frm([['Action on Completion', pick('onDone', U.onDone || 'Return to Home', ['Return to Home', 'Hover at Final Point', 'Precision Land', 'Continue to Next Mission']), 'raw']])}<div class="row mt">${UI.btn('Simulate', { go: 'plan/simulate', icon: 'play' })}${UI.btn('Save Mission', { primary: 1, toast: 'Mission saved as draft', done: 'Saved' })}</div>`)}</div></div>
    <div class="grid g3">
      ${UI.card('Mission Preview', UI.cam({ img: U.key === 'dam' ? 'preview-3d.jpg' : U.img, live: false, label: '2D Map · 3D View · Coverage', go: 'plan/simulate', foot: 'Open the full simulation', time: `00:00 / ${U.minutes}:00` }))}
      ${UI.card(`Waypoints (${U.waypoints})`, UI.table([{ k: 'n', label: '#' }, { k: 'lat', label: 'Latitude' }, { k: 'lon', label: 'Longitude' }, { k: 'alt', label: 'Altitude (m)', r: 1 }, { k: 'a', label: 'Action' }], Array.from({ length: 7 }, (_, i) => ({ n: i + 1, lat: (U.lat + i * .0006 + (i % 2) * .0002).toFixed(4), lon: (U.lon + i * .0013).toFixed(4), alt: U.alt, a: `<a>${U.key === 'refinery' && i % 3 === 2 ? 'Hover 8 s' : 'Capture'}</a>` }))), { right: '<a data-act="Waypoints regenerated from the area and overlap settings">Auto Generate</a>' })}
      ${UI.card('Coverage &amp; Elevation', C.line({ h: 150, labels: km, xTicks: 5, unit: 'm', yMin: Math.max(0, U.minTerrain - 60), yMax: U.maxTerrain + U.alt + 40, series: [{ name: 'Terrain elevation (m)', data: prof.map(Math.round), color: 'var(--s3)', area: 1 }, { name: 'Flight altitude (m)', data: prof.map(v => Math.round(Math.max(v + U.clearance, U.minTerrain + U.alt * .8))), color: 'var(--s1)', dash: 1 }] }) + UI.statRow([[`${U.maxTerrain} m`, 'Max terrain'], [`${U.minTerrain} m`, 'Min terrain'], [`${U.alt} m AGL`, 'Flight altitude'], [`${U.clearance} m`, 'Clearance (min)']]), { right: `<a data-go="plan/coverage">Coverage plan ${I('chev')}</a>` })}</div>`; });

  /* ---------- Plan · Swarm Configuration ---------- */
  views.swarm = view('swarm', U => { const f = VQ.state.form || (U.key === 'highway' ? 'line' : U.key === 'refinery' ? 'orbit' : 'grid'), n = U.drones.length;
    const k = (U.spacing || 50) / 50, ring = Array.from({ length: n }, (_, i) => [Math.cos(i / n * 2 * Math.PI - Math.PI / 2) * 52, Math.sin(i / n * 2 * Math.PI - Math.PI / 2) * 34]), pos = ({ grid: n <= 3 ? [[0, -30], [-60, 25], [60, 25]] : Array.from({ length: n }, (_, i) => [(i % 3 - 1) * 60, (Math.floor(i / 3) - .5) * 55]), v: Array.from({ length: n }, (_, i) => i === 0 ? [0, -34] : [(i % 2 ? -1 : 1) * Math.ceil(i / 2) * 42, -34 + Math.ceil(i / 2) * 28]), line: Array.from({ length: n }, (_, i) => [(i - (n - 1) / 2) * 60, 0]), orbit: ring })[f].map(p => [p[0] * k, p[1] * k]);
    return `<div class="grid g-2-1"><div class="col">
      ${UI.card(`Drones and roles (${n})`, `<div class="list">${U.drones.map((d, i) => droneRow(d, `<div style="min-width:150px"><div class="fld edit"><select onchange="VQ.ops.editDrone(${i},'role',this.value)" aria-label="Role">${['Lead · Mapping', 'Lead · Patrol', 'Lead · Thermal', 'Survey', 'Thermal', 'Mapping', 'Relay', 'Gas survey'].map(r => `<option ${r === d.role ? 'selected' : ''}>${r}</option>`).join('')}</select>${I('chevd')}</div></div><div class="small t2" style="min-width:150px">${d.sector}</div><span class="batt"><i style="--p:${d.batt}%;--c:var(--good)"></i>${d.batt}%</span>${n > 1 ? `<button class="btn sm ghost" style="min-width:0" onclick="VQ.ops.editDrone(${i},'remove')" data-tip="Remove from the swarm">${I('x')}</button>` : ''}`)).join('')}</div><div class="row mt">${n < 6 ? `<button class="btn sm" onclick="VQ.ops.editDrone(0,'add')">${I('plus')}Add Drone</button>` : ''}${UI.btn('Auto Assign Roles', { sm: 1, toast: 'Roles assigned from payloads and battery' })}<span class="small t2">Mission time is now <b class="ink">${U.minutes} min</b> with ${n} drone${n > 1 ? 's' : ''}</span></div><div class="card-note mt">Roles available: Lead, Survey, Thermal, Mapping, Relay. The lead carries the mission clock; the others hold formation against it.</div>`, { icon: 'net' })}
      <div class="grid g2" style="margin:0">${UI.card('Task allocation', UI.table([{ k: 'd', label: 'Drone' }, { k: 's', label: 'Task' }, { k: 'p', label: 'Share', r: 1 }, { k: 't', label: 'Time', r: 1 }], U.drones.map((d, i) => ({ d: `<b class="ink">${d.name}</b>`, s: d.sector, p: d.role === 'Relay' ? '—' : Math.round(100 / (n - (U.key === 'highway' ? 1 : 0))) + '%', t: `${U.minutes - i * 2} min` }))) + `<div class="card-note mt">Allocated by ${U.key === 'highway' ? 'carriageway and distance' : U.key === 'refinery' ? 'asset and sensor' : 'sector area'}, balanced so every drone lands with at least 25% battery.</div>`)}
        ${UI.card('If a drone drops out', frm([['Policy', 'Re-split remaining task'], ['Who takes over', 'Nearest drone with battery'], ['Minimum swarm size', n - 1, 'drones'], ['If the lead drops', 'Promote Drone 2'], ['If below minimum', 'All return to home']]) + `<div class="insight mt" style="margin-bottom:0"><span style="color:var(--violet)">${I('sparkles')}</span><div><b>What that costs</b><p>Losing one drone adds about ${Math.round(U.minutes * .4)} minutes and keeps coverage at ${U.coverage - 3}%.</p></div></div>`)}</div></div>
      <div class="col">${UI.card('Formation', opts([['grid', 'Area split', 'grid'], ['v', 'V formation', 'chevd'], ['line', 'Line abreast', 'minus'], ['orbit', 'Orbit', 'refresh']], f, 'form') + `<svg viewBox="-160 -90 320 180" style="width:100%;height:170px;margin-top:8px;border:1px dashed var(--axis);border-radius:10px;background:var(--blue-50)">${pos.map((p, i) => pos.slice(i + 1).map(q => `<line x1="${p[0]}" y1="${p[1]}" x2="${q[0]}" y2="${q[1]}" stroke="var(--axis)" stroke-dasharray="4 4"/>`).join('')).join('')}${pos.map((p, i) => `<g transform="translate(${p[0]},${p[1]})"><circle r="15" fill="${Object.values(VQ.MMap.COL)[i]}"/>${VQ.iconG('drone', 0, 0, 17, '#fff', 2)}<text y="31" text-anchor="middle" style="font-size:10px;fill:var(--text-2);font-family:Inter">${U.drones[i].role.split(' · ')[0]}</text></g>`).join('')}</svg>`, { right: `<span class="small">Swarm Alpha · ${n} drones</span>` })}
        ${UI.card('Separation', `<div class="col" style="gap:12px"><div><div class="row between small t2 mb"><span>Horizontal spacing</span><b class="ink">${U.spacing || 50} m</b></div><input type="range" min="20" max="120" step="5" value="${U.spacing || 50}" style="width:100%;accent-color:var(--blue)" onchange="VQ.ops.edit('spacing',this.value)" oninput="this.previousElementSibling.querySelector('b').textContent=this.value+' m'"></div><div><div class="row between small t2 mb"><span>Altitude separation</span><b class="ink">${U.altSep || 10} m steps</b></div><input type="range" min="5" max="30" step="5" value="${U.altSep || 10}" style="width:100%;accent-color:var(--blue)" onchange="VQ.ops.edit('altSep',this.value)" oninput="this.previousElementSibling.querySelector('b').textContent=this.value+' m steps'"></div><div><div class="small t2 mb">Minimum distance (hard limit)</div>${sld(25, '15 m')}</div></div><div class="card-note mt">Altitudes: ${U.drones.map((d, i) => `${d.name} ${U.alt + i * (U.altSep || 10)} m`).join(' · ')}. Swarm width ${(U.spacing || 50) * Math.max(1, n - 1)} m.</div>`)}</div></div>`; });

  /* ---------- Plan · Scheduling ---------- */
  views.schedule = view('schedule', U => { const hrs = ['06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17']; const start = U.key === 'refinery' ? 4 : U.key === 'highway' ? 3.5 : 3.2;
    const rows = [['This mission', start, U.minutes / 60, 'var(--blue)'], ['Weather window', 3, 2.2, 'var(--good)'], [`${U.drones[0].id} availability`, 2.9, 5, 'var(--s3)'], [`${U.drones[1].id} availability`, 3.6, 4, 'var(--s3)'], ['Charging (after)', start + U.minutes / 60, .9, 'var(--warn)'], ['Conflict: M-2026-005 shares ' + U.drones[1].id, 4.5, .8, 'var(--crit)']];
    return `<div class="grid g-1-2">${UI.card('When', frm([['Mission date', '16 Sep 2026'], ['Launch time', U.key === 'refinery' ? '10:00 AM' : U.key === 'highway' ? '09:30 AM' : '09:15 AM'], ['Estimated duration', `${U.minutes} min`, ' '], ['Preferred window', '09:00 – 11:00 AM'], ['Recurrence', U.key === 'highway' ? 'Every 2 hours, daily' : U.key === 'refinery' ? 'Weekly, Tuesday' : 'Monthly, first Tuesday'], ['Time zone', 'IST (UTC +5:30)', ' ']]) + `<div class="row between mt"><span class="t2">Skip automatically if the weather window closes</span>${sw(1)}</div><div class="row between mt"><span class="t2">Notify operator 15 minutes before launch</span>${sw(1)}</div>`, { icon: 'cal' })}
      ${UI.card('Today, 06:00 to 18:00', `<div style="display:grid;grid-template-columns:190px 1fr;font-size:12px;row-gap:6px;align-items:center"><div></div><div style="display:grid;grid-template-columns:repeat(12,1fr);color:var(--muted);font-size:10.5px">${hrs.map(h => `<span>${h}:00</span>`).join('')}</div>${rows.map(r => `<div class="t2">${r[0]}</div><div style="position:relative;height:18px;background:var(--blue-50);border-radius:4px"><i style="position:absolute;left:${r[1] / 12 * 100}%;width:${r[2] / 12 * 100}%;top:0;bottom:0;border-radius:4px;background:${r[3]}"></i></div>`).join('')}</div><div class="card-note mt">The mission fits inside the weather window and both drones’ availability.</div>`)}</div>
    <div class="grid g3">${UI.card('Conflicts', chk('warn', `${U.drones[1].id} is also booked on M-2026-005 at 10:30 AM`, 'There are 18 minutes between landing and the next launch; a battery swap needs 12. Tight but workable.') + `<div class="mt"></div>` + chk('ok', 'No airspace booking overlaps', 'Nearest other mission is 6.4 km away.'), { icon: 'alert' })}
      ${UI.card('Battery and charging', UI.table([{ k: 'd', label: 'Drone' }, { k: 'n', label: 'Now', r: 1 }, { k: 'u', label: 'Mission uses', r: 1 }, { k: 'l', label: 'Lands with', r: 1 }], U.drones.map((d, i) => ({ d: d.name, n: d.batt + '%', u: (52 + i * 4) + '%', l: `<b class="ink">${d.batt - 52 - i * 4}%</b>` }))) + '<div class="card-note mt">Reserve rule: land with 25% or more. All drones comply.</div>')}
      ${UI.card('Crew and approvals', UI.list([{ icon: 'user', tone: 'info', title: 'Pilot in command', sub: 'Shift A remote pilot · on duty until 02:00 PM', pill: UI.pill('Available', 'good') }, { icon: 'eye', tone: 'info', title: 'Visual observer', sub: U.key === 'highway' ? 'Patrol vehicle at Km 85' : 'On site from 09:00 AM', pill: UI.pill('Confirmed', 'good') }, { icon: 'shieldcheck', tone: 'warn', title: 'Operator approval', sub: 'Needed before launch', pill: UI.pill('Pending', 'warn') }]))}</div>`; });

  /* ---------- Plan · Coverage & Capture ---------- */
  views.coverage = view('coverage', U => `${UI.kpis([{ icon: 'grid', bg: 'bg-info', value: U.coverage + '%', label: 'Expected coverage' }, { icon: 'video', bg: 'bg-navy', value: VQ.fmt(U.images), label: 'Images (estimated)' }, { icon: 'ruler', bg: 'bg-violet', value: U.gsd, unit: 'cm/px', label: 'Ground sampling distance' }, { icon: 'db', bg: 'bg-serious', value: '~' + U.dataGB, unit: 'GB', label: 'Estimated data volume' }, { icon: 'shieldcheck', bg: 'bg-good', value: U.confidence + '%', label: 'Coverage confidence' }], 'g5')}
    <div class="grid g-2-1"><div class="card flush">${VQ.MMap.render({ uc: U.key, h: 400, layers: { area: 1, path: 1, sectors: 1, comms: 0, drones: 0 }, labels: false, showLayers: [['area', 'Coverage Area'], ['sectors', 'Coverage by drone'], ['path', 'Flight lines'], ['waypoints', 'Capture points'], ['obst', 'Obstacles']] })}</div>
      <div class="col">${UI.card('Capture plan', frm([['Front overlap', U.overlapF, '%'], ['Side overlap', U.overlapS, '%'], ['Flight altitude', U.alt, 'm AGL'], ['Capture interval', U.interval, 'sec'], ['Line spacing', Math.round(U.alt * .42), 'm'], ['Image footprint', `${Math.round(U.alt * 1.2)} × ${Math.round(U.alt * .9)}`, 'm']]))}
        ${UI.card('Blind spots', chk('warn', `${U.blind.split(' ')[0]} area${U.blind[0] === '1' ? '' : 's'} the plan cannot see`, U.blind.replace(/^\d+ \(|\)$/g, '') + '.') + `<div class="mt"></div>${UI.btn('Add oblique passes', { sm: 1, toast: 'Two oblique passes added: +3 minutes, coverage +2%', done: 'Added' })}`)}</div></div>
    <div class="grid g2">${UI.card('Coverage by drone', C.hbars({ unit: '%', max: 100, items: U.drones.filter(d => d.role !== 'Relay').map((d, i) => ({ label: `${d.name} · ${d.role}`, value: Math.round(U.coverage / U.drones.filter(x => x.role !== 'Relay').length) + (i ? -1 : 2), icon: 'drone' })) }) + `<div class="card-note">Shares add up to the ${U.coverage}% expected coverage.</div>`)}
      ${UI.card('What drives confidence', UI.factors([{ title: 'Overlap meets the reconstruction minimum', text: `${U.overlapF}% front, ${U.overlapS}% side`, pct: 30 }, { title: 'Terrain following keeps GSD steady', text: `GSD stays within ±0.3 cm of ${U.gsd}`, pct: 24 }, { title: 'Shadowed or occluded faces', text: U.blind.replace(/^\d+ \(|\)$/g, ''), pct: 58 }]) + '<div class="card-note mt">Longer bars reduce confidence more.</div>')}</div>`);

  /* ---------- Payload · Payload Configuration (mockup 05) ---------- */
  views.payload = view('payload', U => { const cat = VQ.state.pcat || 'All', sel = VQ.state.pl || 'rgb', P = D.payloads.find(p => p.id === sel), list = D.payloads.filter(p => cat === 'All' || p.cat === cat), types = new Set(U.drones.flatMap(d => [d.p1, d.p2]));
    return `<div class="card mb" style="display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;align-items:center">${[['drone', U.drones.length, 'Drones Selected'], ['video', types.size, 'Payload Types'], ['db', `~${U.dataGB} GB`, 'Estimated Data'], ['clock', `${U.minutes} min`, 'Est. Flight Time']].map(k => `<div class="row"><span style="width:30px;height:30px;color:var(--ink)">${I(k[0])}</span><div><div class="kpi-val" style="font-size:17px">${k[1]}</div><div class="kpi-lbl">${k[2]}</div></div></div>`).join('')}<div class="row"><span style="width:28px;height:28px;color:var(--good)">${I('checkc')}</span><div><b style="color:var(--good-ink)">Compatible</b><div class="kpi-lbl">All payloads supported</div></div></div></div>
    <div class="grid g2"><div class="col">
      ${UI.card('Payload Catalog', `<div class="card-note mb">Select from a wide range of payloads and sensors.</div>${UI.seg('pcat', ['All', 'Imaging', 'Mapping', 'Environmental', 'Inspection', 'Security', 'Other'].map(c => [c, c]), cat)}<div class="pcat mt">${list.map(p => `<div class="pc ${p.id === sel ? 'on' : ''}" data-set="pl=${p.id}"><img src="assets/img/${p.img}" alt=""><b>${p.name}</b><span>${p.text}</span><div class="tags">${p.tags.map(t => `<i class="tagc" style="font-style:normal">${t}</i>`).join('')}</div></div>`).join('')}</div>`)}
      ${UI.card('Payload Configuration', `<div class="grid g2" style="margin:0"><div><div class="b ink small mb" style="color:var(--blue-600)">Capture Settings</div>${frm([['Resolution', sel === 'thermal' ? '640 × 512' : '4K (3840 × 2160)'], ['Capture Mode', 'Timed Interval'], ['Interval', `${U.interval} sec`], ['Gimbal Angle', U.key === 'refinery' ? 'Oblique (45°)' : 'Nadir (90°)'], ['Zoom', sel === 'zoom' ? '12× optical' : '1×'], ['Image Format', sel === 'thermal' ? 'R-JPEG + Geotag' : 'JPEG + Geotag']])}<div class="row between mt"><span class="t2">Record Video</span>${sw(1)}</div><div class="row between mt"><span class="t2">Save to Onboard Storage</span>${sw(1)}</div></div>
        <div><div class="b ink small mb" style="color:var(--blue-600)">Advanced Settings</div>${frm([['Exposure', 'Auto'], ['White Balance', 'Auto'], ['ISO Range', '100 – 1600'], ['Focus Mode', 'Auto'], ['Overlap (Mapping)', `Front ${U.overlapF}% | Side ${U.overlapS}%`], ['Storage', '512 GB card']])}<div class="row between mt"><span class="t2">Geotagging</span>${sw(1)}</div><div class="row between mt"><span class="t2">Real-time Streaming</span>${sw(1)}</div></div></div>`, { right: `<span class="sel">${U.drones[0].name} – ${P.name}${I('chevd')}</span>` })}</div>
    <div class="col">
      ${UI.card('Selected Payloads (Per Drone)', `<div class="card-note mb">Assign payloads to each drone in the mission.</div><div class="list">${U.drones.map(d => droneRow(d, `<div style="min-width:150px">${fld(`${d.p1}<br><em>Primary</em>`)}</div><div style="min-width:150px">${fld(`${d.p2}<br><em>Secondary</em>`)}</div>`)).join('')}</div>`, { right: UI.btn('Auto Assign', { sm: 1, toast: 'Payloads assigned from the capture objectives' }) })}
      ${UI.card('Drone → Payload → Capture Objective', UI.table([{ k: 'd', label: 'Drone' }, { k: 'p', label: 'Payload' }, { k: 'o', label: 'Capture objective' }], U.drones.flatMap(d => [{ d: `<b class="ink">${d.name}</b>`, p: d.p1, o: objective(d.p1, U) }, { d: '', p: d.p2, o: objective(d.p2, U) }])))}
      <div class="grid g2" style="margin:0">${UI.card('Payload Preview', `<img src="assets/img/payload-preview.jpg" alt="" style="width:100%;height:150px;object-fit:cover;border-radius:8px"><div class="b ink mt">${P.name}</div><div class="small t2">${P.text}</div><div class="row wrap mt" style="gap:4px">${P.tags.map(t => `<i class="tagc" style="font-style:normal">${t}</i>`).join('')}<i class="tagc" style="font-style:normal">${P.stock} in stock</i></div>`)}
        ${UI.card('Sample Output', UI.cam({ img: sel === 'thermal' || sel === 'gas' ? 'th-thermal.jpg' : U.img, live: false, cls: sel === 'multi' ? 'thermal' : '' }) + `<div class="small t2 mt">${sel === 'thermal' ? 'Radiometric thermal imagery with per-pixel temperature.' : sel === 'lidar' ? 'Dense point cloud for 3D models and measurements.' : 'High-resolution, geotagged imagery for asset inspection and mapping.'}</div>`)}</div>
      ${UI.card('Estimated Data Volume', UI.statRow([[`~${Math.round(U.dataGB * .38)} GB`, `Images, for a ${U.minutes} min mission`], [VQ.fmt(U.images), 'Images (est.)'], [`~${Math.round(U.dataGB * .28)} GB`, 'Video (optional)']]) + `<div class="card-note mt">Images, video and ${U.key === 'dam' ? 'LiDAR point cloud' : U.key === 'refinery' ? 'gas sensor log' : 'thermal stream'} together come to about ${U.dataGB} GB.</div>`)}</div></div>`; });
  const objective = (p, U) => ({ 'RGB Camera': 'Orthomosaic and visual defect record', 'Thermal Camera': U.key === 'dam' ? 'Seepage: cold bands on the downstream slope' : U.key === 'highway' ? 'People and vehicles at night or in fog' : 'Hot spots on column, flanges and insulation', LiDAR: '3D model of the dam face to 3 cm', Multispectral: 'Vegetation growth on the embankment (NDVI)', 'Zoom Camera': U.key === 'highway' ? 'Number plates and lane-level detail from 30 m off the road' : 'Close-up of flanges without approaching', 'Gas Sensor': 'Hydrocarbon and H₂S readings on downwind legs', 'Speaker / Siren': 'Warn road users at an incident', 'Comms relay': 'Extends the radio link past Km 85' }[p] || 'Supporting capture');

  /* ---------- Payload · AI Detection ---------- */
  const DET = [['people', 'People', 'walk', 85], ['vehicles', 'Vehicles', 'car', 80], ['smoke', 'Smoke / Fire', 'flame', 75], ['thermal', 'Thermal anomalies', 'thermo', 80], ['vegetation', 'Vegetation', 'leaf', 70], ['cracks', 'Cracks', 'pulse', 85], ['water', 'Water / Seepage', 'drop', 80], ['objects', 'Objects / Debris', 'box', 75], ['defects', 'Asset defects', 'wrench', 85]];
  views.ai = view('ai', U => `<div class="grid g-2-1"><div class="col">
      ${UI.card('What should this mission look for?', `<div class="opt-grid" style="grid-template-columns:repeat(auto-fill,minmax(118px,1fr))">${DET.map(d => `<button class="opt ${U.detect.includes(d[0]) ? 'on' : ''}" onclick="this.classList.toggle('on')">${I(d[2])}<span>${d[1]}</span></button>`).join('')}</div><div class="card-note mt">${U.detect.length} detectors on for this use case. Each runs on the drone; only alerts and clips are streamed.</div>`, { icon: 'sparkles' })}
      ${UI.card('Thresholds and alert rules', UI.table([{ k: 'd', label: 'Detector' }, { k: 'c', label: 'Alert when confidence is at least' }, { k: 'r', label: 'What counts as an alert' }, { k: 'a', label: 'Then' }], DET.filter(d => U.detect.includes(d[0])).map(d => ({ d: `<b class="ink">${d[1]}</b>`, c: `<div style="min-width:150px">${sld(d[3], d[3] + '%')}</div>`, r: rule(d[0], U), a: d[0] === 'smoke' || d[0] === 'people' ? UI.pill('Alert + hold position', 'crit') : UI.pill('Alert + tag frame', 'info') }))))}</div>
    <div class="col">${UI.card('Sample detection', UI.cam({ img: U.key === 'dam' ? 'th-zoom.jpg' : U.key === 'highway' ? 'hw-cam-stalled-truck.jpg' : 'ref-cam-column.jpg', live: false, label: 'Preview on last flight’s footage', boxes: [U.key === 'highway' ? { x: 40, y: 33, w: 20, h: 44, label: 'Vehicle · stationary · 91%', tone: 'crit' } : U.key === 'dam' ? { x: 30, y: 30, w: 26, h: 40, label: 'Crack candidate · 87%', tone: 'warn' } : { x: 38, y: 12, w: 24, h: 50, label: 'Thermal anomaly · 93%', tone: 'crit' }] }))}
      ${UI.card('Where alerts go', UI.list([{ icon: 'bell', tone: 'info', title: 'Command Center', sub: 'Every alert, with clip and position' }, { icon: 'users', tone: 'info', title: U.key === 'highway' ? 'Highway control room' : U.key === 'refinery' ? 'Refinery shift in charge' : 'Dam safety engineer', sub: 'High and critical only' }, { icon: 'file', tone: 'info', title: 'Mission report', sub: 'All detections, reviewed or not' }]) + `<div class="row between mt"><span class="t2">Human review before an alert is sent on</span>${sw(U.key !== 'highway')}</div>`)}
      ${UI.card('Model', UI.kv([['cpu', 'Detection model', 'VizionIQ Vision 4.2'], ['shieldcheck', 'Validated precision', '92% on this use case'], ['zap', 'Runs on', 'Drone edge computer'], ['clock', 'Latency', 'Under 400 ms']]))}</div></div>`);
  const rule = (k, U) => ({ people: U.key === 'refinery' ? 'Anyone inside the unit cordon' : 'Anyone inside the mission area', vehicles: U.key === 'highway' ? 'Stationary in a live lane over 3 minutes, or moving against traffic' : 'Any vehicle inside the area', smoke: 'Any smoke or flame, 3 frames in a row', thermal: U.key === 'dam' ? 'Band 3°C colder than the slope around it' : 'Surface 25°C above its baseline', vegetation: 'Woody growth on the embankment', cracks: 'Crack longer than 0.5 m or wider than 5 mm', water: 'Standing or flowing water on the downstream face', objects: U.key === 'highway' ? 'Object larger than 0.3 m in a live lane' : 'Foreign object on the asset', defects: 'Corrosion, missing insulation, loose cladding' }[k]);

  VQ.screen('plan', { ws: 'ops', title: 'Mission Planning', head, views });
  return { view, fld, frm, sw, sld, opts, chk, droneRow, SEQ, label };
})();
