/* Mission Planning · hard gates. The geofence, the readiness exceptions and the plan upload really lock Launch.
   State lives in storage (breach, batt, appr, up) so it carries across the planning screens. */
(() => {
  const { UI, I } = VQ, D = VQ.ops, P = VQ.Plan, V = VQ.SCREENS.plan.views, { view, chk } = P;
  const G = D.gate = () => ({ breach: VQ.store.get('breach', 0), batt: VQ.store.get('batt', 0), appr: VQ.store.get('appr', 0), up: VQ.store.get('up', 0) });
  window.VQgate = (k, v, msg) => { VQ.store.set(k, v); if (k === 'breach' && v) VQ.store.set('up', 0); if (msg) VQ.toast(msg); VQ.render(true); };
  const launchAt = U => U.key === 'refinery' ? '10:00 AM' : U.key === 'highway' ? '09:30 AM' : '09:15 AM';

  /* Geofencing & Safety: enforcement card on top of the existing screen */
  const g0 = V.geofence.render;
  V.geofence = { render: ctx => { const g = G();
    return `<div class="card mb" style="border-left:4px solid var(--${g.breach ? 'crit' : 'good'})"><div class="row between wrap"><div class="row">${`<span style="width:26px;height:26px;color:var(--${g.breach ? 'crit' : 'good'})">${I(g.breach ? 'octagon' : 'shieldcheck')}</span>`}<div><b class="ink" style="font-size:14px">${g.breach ? 'BOUNDARY CHECK FAILED · waypoint 14 is inside a no-fly zone' : 'BOUNDARY CHECK PASSED · geofence active'}</b><div class="small t2">The geofence is a hard gate: a plan that breaches it cannot be saved as ready, uploaded to a drone, or launched.</div></div></div>
      <div class="row">${g.breach ? `<button class="btn primary" onclick="VQgate('breach',0,'Waypoint 14 moved back inside the fence. Boundary check passed.')">${I('refresh')}Auto-fix the route</button>` : `<button class="btn ghost" onclick="VQgate('breach',1,'Waypoint 14 dragged into the no-fly zone. Upload and launch are now blocked.')">${I('alert')}Try it: drag a waypoint into the no-fly zone</button>`}</div></div></div>` + g0(ctx); } };

  V.readiness = view('readiness', U => { const g = G(), last = U.drones[U.drones.length - 1], lands = last.batt - 52 - (U.drones.length - 1) * 4;
    const items = [['drone', 'Drone Ready', 'ok', `${U.drones.length} of ${U.drones.length} passed self-test, firmware current`], ['video', 'Payload Ready', 'ok', 'All payloads mounted and calibrated'], ['mappin', 'Airspace Clear', 'ok', 'Permission valid, no advisories on the route'], ['sun', 'Weather Acceptable', 'ok', 'Inside limits until 11:10 AM'],
      ['battery', 'Battery Ready', g.batt ? 'ok' : 'warn', g.batt ? `${last.name} has a fresh pack at 100%` : `${last.name} at ${last.batt}%: lands with ${lands}%, close to the 25% reserve rule`], ['wifi', 'Connectivity Ready', 'ok', 'RF and cellular links tested'],
      ['route', 'Route Validated', g.breach ? 'bad' : 'ok', g.breach ? 'Waypoint 14 is inside a no-fly zone' : 'Inside the geofence; simulation found no conflicts'], ['user', 'Operator Approval', g.appr ? 'ok' : 'bad', g.appr ? `Approved by ${D.user}, 08:42 AM` : 'Waiting for the pilot in command to sign off']];
    const ex = items.filter(i => i[2] !== 'ok');
    return `<div class="banner ${ex.length ? 'medium' : 'low'} mb">${I(ex.length ? 'alert' : 'checkc')}<div><div class="k">Mission Readiness</div><div class="v">${items.length - ex.length} of ${items.length} ready</div></div><div class="d">${ex.length ? `<b>${ex.length} exception${ex.length > 1 ? 's' : ''} before launch:</b><br>${ex.map(e => e[1]).join(' · ')}` : '<b>No exceptions.</b><br>The mission can be launched.'}</div></div>
    <div class="grid g4">${items.map(i => `<div class="card" style="border-top:4px solid var(--${i[2] === 'ok' ? 'good' : i[2] === 'warn' ? 'warn' : 'crit'})"><div class="row between"><span style="width:28px;height:28px;color:var(--ink)">${I(i[0])}</span>${UI.pill(i[2] === 'ok' ? 'Ready' : i[2] === 'warn' ? 'Check' : i[0] === 'route' ? 'Blocked' : 'Pending', i[2] === 'ok' ? 'good' : i[2] === 'warn' ? 'warn' : 'crit')}</div><div class="b ink mt" style="font-size:14px">${i[1]}</div><div class="small t2">${i[3]}</div></div>`).join('')}</div>
    <div class="grid g2">${UI.card('Exceptions', (ex.length ? ex.map(e => chk(e[2], e[1], e[3])).join('<div class="mt"></div>') : chk('ok', 'Nothing open', 'All eight checks are ready.')) + `<div class="row wrap mt">${g.batt ? '' : `<button class="btn sm" onclick="VQgate('batt',1,'Battery swapped on ${last.name}: 100%')">Swap battery on ${last.name}</button>`}${g.breach ? UI.btn('Fix the route in Geofencing', { sm: 1, go: 'plan/geofence' }) : ''}${g.appr ? '' : `<button class="btn sm primary" onclick="VQgate('appr',1,'Mission approved by ${D.user}')">Approve as pilot in command</button>`}${ex.length ? '' : `<button class="btn sm ghost" onclick="VQgate('batt',0);VQgate('appr',0,'Readiness reset')">Reset the demo checks</button>`}</div>`, { icon: 'alert' })}
      ${UI.card('Pre-flight checklist', UI.steps(['Propellers, arms and landing gear inspected.', 'Payload lens clean, storage card empty.', 'Home point and emergency landing zones confirmed on site.', 'Observers in position and on the radio.', 'Launch area clear of people.']) + `<div class="row mt">${UI.btn('Summary & Launch', { primary: 1, go: 'plan/launch' })}</div>`)}</div>`; });

  V.launch = view('launch', U => { const g = G(), open = [g.breach && 'geofence breach', !g.batt && 'battery check', !g.appr && 'operator approval', !g.up && 'flight plan not uploaded'].filter(Boolean), ok = !open.length;
    return `<div class="grid g-2-1"><div class="col">
      ${UI.card(U.name, `<div class="mb">${U.objective}</div>${UI.facts([['mappin', 'Location', U.location], ['route', 'Route', `${U.pattern} · ${U.waypoints} waypoints`], ['drone', 'Drones', `${U.drones.length} (${U.drones.map(d => d.role.split(' · ')[0]).join(', ')})`], ['video', 'Payloads', [...new Set(U.drones.flatMap(d => [d.p1, d.p2]))].join(', ')], ['clock', 'Duration', `${U.minutes} min, launch ${launchAt(U)}`], ['grid', 'Coverage', `${U.coverage}% · GSD ${U.gsd} cm · ${VQ.fmt(U.images)} images`], ['db', 'Data', `~${U.dataGB} GB`], ['sun', 'Weather window', '09:00 – 11:10 AM']])}`, { icon: 'file', right: UI.pill(U.id, 'info') })}
      <div class="grid g2" style="margin:0">${UI.card('Risks', UI.list(U.risks.map(r => ({ icon: 'alert', tone: 'warn', title: r }))))}${UI.card('Mission rules', UI.steps(['Maximum altitude 120 m AGL; geofence buffer 20 m.', 'Land with 25% battery or more.', 'On link loss: continue 60 s, then return by the safe corridor.', `Alerts on: ${U.detect.join(', ')}.`]))}</div></div>
    <div class="col"><div class="card flush">${VQ.MMap.render({ uc: U.key, h: 240, labels: false, layers: { area: 1, path: 1, nfz: 1, drones: 0 } })}</div>
      ${UI.card('Upload flight plan', g.breach ? chk('bad', 'Upload blocked: geofence breach', 'The mission path breaches the active geofence. Fix the route first.') + `<div class="row mt">${UI.btn('Open Geofencing', { sm: 1, go: 'plan/geofence' })}</div>` : g.up ? chk('ok', `Plan on all ${U.drones.length} drones`, `${U.waypoints} waypoints, checksum verified on each autopilot.`) : chk('warn', 'Not uploaded yet', `${U.waypoints} waypoints, ${U.minutes} min, max altitude ${U.alt + 10} m.`) + `<div class="row mt"><button class="btn sm primary" onclick="VQgate('up',1,'Flight plan sent to ${U.drones.length} drones and verified')">${I('download')}Upload to Drones</button></div>`, { icon: 'download' })}
      ${UI.card('Readiness', chk(ok ? 'ok' : 'warn', ok ? 'Ready to launch' : `${open.length} thing${open.length > 1 ? 's' : ''} still open`, ok ? 'All eight checks passed and the plan is on the drones.' : open.join(' · ') + '.') + `<div class="mt"><a data-go="plan/readiness">Open Mission Readiness ${I('chev')}</a></div>`)}</div></div>
    ${UI.card('Decision', `<div class="launch-row">${UI.btn('Schedule Mission', { icon: 'cal', toast: `${U.id} scheduled for 16 Sep, ${launchAt(U)}`, done: 'Scheduled' })}${ok ? `<button class="btn primary" onclick="VQ.toast('${U.id} launch sequence started. Opening Live Operations.');setTimeout(()=>VQ.go('live'),900)">${I('play')}Launch Mission</button>` : `<button class="btn" disabled style="opacity:.5;cursor:not-allowed" data-tip="Locked: ${open.join(', ')}">${I('lock')}Launch Mission (locked)</button>`}<span class="t2" style="align-self:center">${ok ? 'Everything is clear.' : 'Launch unlocks when the geofence check passes, both readiness exceptions are cleared and the plan is uploaded.'}</span></div>`, { cls: 'mb' })}`; });
})();
