/* =========================================================
   Mission Planning · Safety (geofence, weather, comms) and Advanced (flight, simulate, readiness, launch)
   ========================================================= */
(() => {
  const { UI, C, I } = VQ, D = VQ.ops, P = VQ.Plan, V = VQ.SCREENS.plan.views, { view, frm, sw, sld, chk, fld } = P;
  const launchAt = U => U.key === 'refinery' ? '10:00 AM' : U.key === 'highway' ? '09:30 AM' : '09:15 AM';

  /* ---------- Safety · Geofencing & Safety ---------- */
  V.geofence = view('geofence', U => `<div class="grid g-2-1"><div class="card flush">${VQ.MMap.render({ uc: U.key, h: 480, layers: { area: 1, path: 1, nfz: 1, safe: 1, elz: 1, obst: 1, drones: 0 }, showLayers: [['nfz', 'No-fly and restricted'], ['safe', 'Safe corridors'], ['elz', 'Emergency landing zones'], ['obst', 'Obstacles'], ['area', 'Mission area'], ['path', 'Flight path']] })}</div>
      <div class="col">${UI.card('Limits', frm([['Maximum altitude', 120, 'm AGL'], ['Minimum clearance over terrain', U.clearance, 'm'], ['Clearance from obstacles', 15, 'm'], ['Geofence buffer', 20, 'm'], ['Standoff from people', 30, 'm'], ['If the fence is touched', 'Stop, hover, alert']]), { icon: 'shield' })}
        ${UI.card('Obstacle avoidance', `<div class="row between"><span class="t2">Onboard sensing (6 directions)</span>${sw(1)}</div><div class="row between mt"><span class="t2">Use the terrain and obstacle database</span>${sw(1)}</div><div class="row between mt"><span class="t2">Re-route automatically around a new obstacle</span>${sw(1)}</div><div class="row between mt"><span class="t2">Allow flight over people</span>${sw(0)}</div>`)}</div></div>
    <div class="grid g3">${UI.card('Zones on this mission', UI.table([{ k: 'z', label: 'Zone' }, { k: 't', label: 'Type' }, { k: 'r', label: 'Route' }], [['No-fly zone', 'crit', 'Route avoids it by 35 m'], ['Restricted area', 'warn', 'Crossed above the minimum altitude'], ['Safe corridor out', 'good', 'Used for launch and return'], ['Safe corridor back', 'good', 'Used if the link drops']].map((z, i) => ({ z: i === 0 ? U.risks[2].replace(/^No-fly zone: /, '') : z[0], t: UI.pill(z[0], z[1]), r: z[2] }))))}
      ${UI.card('Return-to-home and emergency landing', UI.list([{ icon: 'home', tone: 'good', title: 'Home · launch pad', sub: 'Primary return point for every drone' }, { icon: 'mappin', tone: 'good', title: 'ELZ-1', sub: 'Nearest for the first half of the route' }, { icon: 'mappin', tone: 'good', title: 'ELZ-2', sub: 'Nearest for the second half of the route' }]) + '<div class="card-note mt">At any point on the route a drone can reach a landing zone with under 4 minutes of flight.</div>')}
      ${UI.card('Route check', chk('ok', 'Route clears every no-fly zone', 'Closest approach 35 m, outside the 20 m buffer.') + '<div class="mt"></div>' + chk('warn', U.risks[0], 'Route crosses it with 22 m to spare. Terrain following is locked off for that leg.') + '<div class="mt"></div>' + chk('ok', 'Airspace permission', 'Green zone. Permission valid today 06:00 AM to 06:00 PM.'))}</div>`);

  /* ---------- Safety · Weather Constraints ---------- */
  V.weather = view('weather', U => { const hrs = ['07:00', '08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00'], wind = [9, 11, 12, 14, 19, 26, 31, 29, 24, 18], gust = [14, 16, 18, 21, 29, 38, 44, 41, 35, 27];
    const lim = [['wifi', 'Wind speed', '12 km/h', 'Limit 30 km/h', 'ok'], ['trend', 'Gusts', '18 km/h', 'Limit 40 km/h', 'ok'], ['rain', 'Precipitation', '0 mm/h', 'Limit 0.5 mm/h', 'ok'], ['eye', 'Visibility', '8 km', 'Minimum 3 km', 'ok'], ['thermo', 'Temperature', '28°C', 'Range 0 to 42°C', 'ok'], ['cloud', 'Cloud ceiling', '900 m', 'Minimum 300 m', 'ok']];
    return `<div class="banner low mb" style="background:var(--good-bg)">${I('checkc')}<div><div class="k">Mission Weather Window</div><div class="v">09:00 AM – 11:10 AM today</div></div><div class="d">Launch ${launchAt(U)} for ${U.minutes} minutes fits with ${U.key === 'refinery' ? 48 : 85} minutes to spare.<br>After 11:10 AM gusts pass the 40 km/h limit${U.key === 'dam' ? ' in the gorge' : ''}.</div></div>
    <div class="grid g-2-1"><div class="col">${UI.card('Forecast along the mission timeline', C.line({ h: 230, labels: hrs, unit: 'km/h', yTitle: 'Wind (km/h)', yMax: 50, limit: { v: 40, label: 'Gust limit 40 km/h' }, band: { from: 5, to: 8, label: 'Outside limits' }, mark: { i: 2, label: 'Launch ' + launchAt(U), color: 'var(--s1)' }, series: [{ name: 'Wind speed', data: wind }, { name: 'Gusts', data: gust, color: 'var(--s2)' }] }) + '<div class="card-note">Gusts cross the limit between 12:00 and 3:00 PM. The mission is planned to be on the ground by then.</div>')}
        ${UI.card('Hour by hour', UI.table([{ k: 'h', label: 'Hour' }, { k: 'w', label: 'Wind', r: 1 }, { k: 'g', label: 'Gust', r: 1 }, { k: 'r', label: 'Rain', r: 1 }, { k: 'v', label: 'Visibility', r: 1 }, { k: 's', label: 'Fly?' }], hrs.slice(1, 8).map((h, i) => ({ h, w: wind[i + 1], g: gust[i + 1], r: i > 4 ? '0.2' : '0', v: i > 4 ? '6 km' : '8 km', s: gust[i + 1] > 40 ? UI.pill('No', 'crit') : gust[i + 1] > 30 ? UI.pill('Marginal', 'warn') : UI.pill('Yes', 'good') }))))}</div>
      <div class="col">${UI.card('Limits and current conditions', `<div class="list">${lim.map(l => `<div class="li" style="align-items:center"><div class="li-ic tone-good">${I(l[0])}</div><div class="li-body"><div class="li-title">${l[1]}</div><div class="li-sub">${l[3]}</div></div><b class="ink">${l[2]}</b></div>`).join('')}</div>`, { icon: 'sun' })}
        ${UI.card('If conditions change in flight', frm([['Wind above limit', 'Pause, then return'], ['Rain detected', 'Return to home'], ['Visibility below minimum', 'Hold and alert'], ['Source', 'Site station + forecast', ' ']]))}</div></div>`; });

  /* ---------- Safety · Communications ---------- */
  V.comms = view('comms', U => `<div class="grid g-2-1"><div class="card flush">${VQ.MMap.render({ uc: U.key, h: 440, layers: { area: 1, path: 1, comms: 1, drones: 1 }, labels: false, showLayers: [['comms', 'Link coverage and gaps'], ['path', 'Flight path'], ['drones', 'Drones'], ['area', 'Mission area']] })}</div>
      <div class="col">${UI.card('Links', UI.table([{ k: 'l', label: 'Link' }, { k: 'r', label: 'Role' }, { k: 's', label: 'Expected' }], [['Drone to controller (RF 2.4 / 5.8 GHz)', 'Primary control', UI.pill('Strong', 'good')], ['Cellular 4G / 5G', 'Video and telemetry backup', UI.pill(U.key === 'highway' ? 'Weak past Km 91' : 'Good', U.key === 'highway' ? 'warn' : 'good')], ['Drone to drone mesh', 'Swarm coordination', UI.pill('Strong', 'good')], ['Satellite', 'Position and last-resort telemetry', UI.pill('Available', 'info')]].map(r => ({ l: `<b class="ink">${r[0]}</b>`, r: r[1], s: r[2] }))), { icon: 'wifi' })}
        ${UI.card('Relay drone', U.key === 'highway' ? chk('ok', 'Drone 3 holds at Km 85, 150 m', 'Extends the radio link to the whole 14 km corridor.') : chk('ok', 'Not needed', 'The ground station sees the whole area except one short shadow.'))}</div></div>
    <div class="grid g3">${UI.card('Expected coverage gaps', chk('warn', U.key === 'dam' ? 'Link shadow behind the east abutment' : U.key === 'highway' ? 'Weak 4G beyond Km 91' : 'Signal shadow behind column C-301', `About ${U.key === 'highway' ? 50 : 35} seconds of the route. The drone flies it on its stored plan and buffers video.`))}
      ${UI.card('Failover order', UI.steps(['RF link drops: switch control to cellular.', 'Cellular also drops: continue the stored route for up to 60 seconds.', 'Still no link: climb to the safe altitude and return by the safe corridor.', 'Battery below reserve at any time: land at the nearest emergency landing zone.']))}
      ${UI.card('Data path', UI.kv([['video', 'Live video', '1080p to the Command Center, 1.2 s delay'], ['db', 'Full-resolution data', 'Onboard storage, uploaded after landing'], ['lock', 'Encryption', 'AES-256 on every link'], ['pulse', 'Telemetry rate', '5 Hz']]))}</div>`);

  /* ---------- Advanced · Flight Parameters ---------- */
  V.flight = view('flight', U => { const seg = [['Launch and climb', 5, `0 → ${U.alt}`, 'Vertical, then transit'], ['Transit to the area', Math.min(15, U.speed + 4), U.alt, 'Safe corridor'], ['Capture legs', U.speed, U.alt, U.pattern], ['Turns', Math.max(2, U.speed - 4), U.alt, 'Coordinated'], ['Return', Math.min(15, U.speed + 4), U.alt + 10, 'Safe corridor'], ['Descent and land', 3, `${U.alt + 10} → 0`, 'Precision landing']];
    const prof = [0, U.alt, U.alt, U.alt + 8, U.alt - 6, U.alt + 4, U.alt, U.alt + 10, U.alt + 10, 0];
    return `<div class="grid g-2-1"><div class="col">${UI.card('Speed and altitude by segment', UI.table([{ k: 's', label: 'Segment' }, { k: 'v', label: 'Speed (m/s)', r: 1 }, { k: 'a', label: 'Altitude (m AGL)', r: 1 }, { k: 'n', label: 'Behaviour' }], seg.map(s => ({ s: `<b class="ink">${s[0]}</b>`, v: s[1], a: s[2], n: s[3] }))), { icon: 'route' })}
        ${UI.card('Altitude profile', C.line({ h: 170, labels: ['Launch', 'Climb', 'Transit', 'Leg 1', 'Leg 2', 'Leg 3', 'Leg 4', 'Return', 'Approach', 'Land'], xTicks: 10, unit: 'm AGL', yMax: 160, limit: { v: 120, label: 'Maximum altitude 120 m' }, series: [{ name: 'Planned altitude (m AGL)', data: prof, area: 1 }] }))}</div>
      <div class="col">${UI.card('Terrain and waypoints', frm([['Terrain following', 'On · 5 m resolution'], ['Waypoint behaviour', U.key === 'refinery' ? 'Stop and capture' : 'Fly through'], ['Turn radius', U.key === 'highway' ? 25 : 12, 'm'], ['Hover duration', U.key === 'refinery' ? 8 : 0, 'sec'], ['Heading', U.key === 'refinery' ? 'Face the asset' : 'Along the track'], ['Acceleration limit', 2.5, 'm/s²']]))}
        ${UI.card('Communication loss and return-to-home', frm([['On link loss', 'Continue 60 s, then return'], ['Return altitude', U.alt + 10, 'm AGL'], ['Return route', 'Safe corridor'], ['Low battery return', 30, '%'], ['Critical battery', 'Land at nearest ELZ']]) + `<div class="row between mt"><span class="t2">Smart return: allow for the headwind</span>${sw(1)}</div>`, { icon: 'home' })}</div></div>`; });

  /* ---------- Advanced · Mission Simulation (full screen) ---------- */
  V.simulate = view('simulate', U => { const N = U.drones.length, ev = [[.02, 'Launch. All drones climb to their separated altitudes.', 'info'], [.12, 'Drones enter their sectors. Capture starts.', 'good'], [.38, `Terrain clearance falls to ${U.clearance + 6} m, still inside the ${U.clearance} m limit.`, 'warn'], [.55, U.key === 'highway' ? 'Drone 2 hands the link to the relay at Km 85.' : 'Drone 2 flies through the link shadow on its stored plan, 35 seconds.', 'warn'], [.74, `Coverage passes ${Math.round(U.coverage * .75)}%. Batteries on plan.`, 'good'], [.96, 'All drones back in the safe corridor. Landing with reserve.', 'good']];
    window.VQsimTick = t => { const q = id => document.getElementById(id), mm = Math.round(t * U.minutes * 60), set = (id, v) => { const e = q(id); if (e) e.textContent = v; };
      set('sm-time', `${String(Math.floor(mm / 60)).padStart(2, '0')}:${String(mm % 60).padStart(2, '0')} / ${U.minutes}:00`); set('sm-cov', Math.round(U.coverage * Math.min(1, Math.max(0, (t - .08) / .84))) + '%'); set('sm-img', VQ.fmt(Math.round(U.images * Math.min(1, Math.max(0, (t - .08) / .84)))));
      set('sm-clear', (t > .34 && t < .44 ? U.clearance + 6 : U.clearance + 28) + ' m'); set('sm-link', t > .52 && t < .58 ? 'Degraded' : 'Strong'); set('sm-wind', Math.round(12 + t * 6) + ' km/h');
      U.drones.forEach((d, k) => { const b = Math.round(d.batt - (52 + k * 4) * t), e = q('sm-b' + k); if (e) e.innerHTML = `<i style="--p:${b}%;--c:var(--${b < 40 ? 'warn' : 'good'})"></i>${b}%`; });
      document.querySelectorAll('[data-ev]').forEach(e => { e.style.opacity = t >= +e.dataset.ev ? 1 : .35; }); };
    return `<div class="grid g-3-1"><div class="card flush"><div style="flex:1;display:flex;flex-direction:column">${VQ.MMap.render({ uc: U.key, h: 470, sim: 'simbar', tick: t => window.VQsimTick(t), layers: { area: 1, path: 1, sectors: 1, nfz: 1, safe: 1, comms: 0, drones: 1 }, showLayers: [['sectors', 'Swarm sectors'], ['path', 'Flight path'], ['nfz', 'No-fly zones'], ['safe', 'Safe corridors'], ['comms', 'Link coverage'], ['weather', 'Wind'], ['obst', 'Obstacles']] })}</div>
        <div class="simbar" id="simbar"><button aria-label="Play or pause">${I('play')}</button><input type="range" min="0" max="1000" value="0" aria-label="Mission time"><span class="num" id="sm-time">00:00 / ${U.minutes}:00</span><span class="pill info">1× = ${U.minutes} min in 15 s</span></div></div>
      <div class="col">${UI.card('Live readout', `<div class="grid g2" style="margin:0;gap:10px">${[['sm-cov', 'Coverage', '0%'], ['sm-img', 'Images captured', '0'], ['sm-clear', 'Terrain clearance', `${U.clearance + 28} m`], ['sm-link', 'Control link', 'Strong'], ['sm-wind', 'Wind', '12 km/h']].map(r => `<div><div class="kpi-val" style="font-size:18px" id="${r[0]}">${r[2]}</div><div class="kpi-lbl">${r[1]}</div></div>`).join('')}</div>`, { icon: 'pulse' })}
        ${UI.card('Battery', `<div class="list">${U.drones.map((d, k) => `<div class="li" style="align-items:center"><div class="li-body"><div class="li-title">${d.name} <span class="muted small">${d.role}</span></div></div><span class="batt" id="sm-b${k}"><i style="--p:${d.batt}%;--c:var(--good)"></i>${d.batt}%</span></div>`).join('')}</div><div class="card-note mt">Lowest landing battery: ${Math.min(...U.drones.map((d, k) => d.batt - 52 - k * 4))}%. Reserve rule is 25%.</div>`)}</div></div>
    <div class="grid g-2-1">${UI.card('What happens, in order', `<div class="vtl">${ev.map(e => `<div class="ev ${e[2] === 'warn' ? 'crit' : e[2] === 'good' ? 'good' : ''}" data-ev="${e[0]}" style="opacity:.35;transition:opacity .3s"><i></i><time>${String(Math.floor(e[0] * U.minutes)).padStart(2, '0')}:${String(Math.round((e[0] * U.minutes % 1) * 60)).padStart(2, '0')}</time>${e[1]}</div>`).join('')}</div>`, { icon: 'clock', right: '<span class="small">Press play, or drag the timeline</span>' })}
      ${UI.card('Simulation result', chk('ok', 'No conflicts found', `${N} drones, minimum separation 38 m against a 15 m limit.`) + '<div class="mt"></div>' + chk('warn', '2 points to watch', 'One low-clearance leg and one short link shadow. Both inside limits.') + `<div class="row mt">${UI.btn('Go to Mission Readiness', { primary: 1, go: 'plan/readiness' })}</div>`)}</div>`; });

  /* ---------- Advanced · Mission Readiness ---------- */
  V.readiness = view('readiness', U => { const items = [['drone', 'Drone Ready', 'ok', `${U.drones.length} of ${U.drones.length} passed self-test, firmware current`], ['video', 'Payload Ready', 'ok', 'All payloads mounted and calibrated'], ['mappin', 'Airspace Clear', 'ok', 'Permission valid, no advisories on the route'], ['sun', 'Weather Acceptable', 'ok', 'Inside limits until 11:10 AM'],
      ['battery', 'Battery Ready', 'warn', `${U.drones[U.drones.length - 1].name} at ${U.drones[U.drones.length - 1].batt}%: lands with ${U.drones[U.drones.length - 1].batt - 52 - (U.drones.length - 1) * 4}%, reserve rule is 25%`], ['wifi', 'Connectivity Ready', 'ok', 'RF and cellular links tested'], ['route', 'Route Validated', 'ok', 'Simulation found no conflicts'], ['user', 'Operator Approval', 'bad', 'Waiting for the pilot in command to sign off']];
    const ex = items.filter(i => i[2] !== 'ok');
    return `<div class="banner ${ex.some(e => e[2] === 'bad') ? 'medium' : 'low'} mb">${I('alert')}<div><div class="k">Mission Readiness</div><div class="v">${items.length - ex.length} of ${items.length} ready</div></div><div class="d"><b>${ex.length} exception${ex.length > 1 ? 's' : ''} before launch:</b><br>${ex.map(e => e[1]).join(' · ')}</div></div>
    <div class="grid g4">${items.map(i => `<div class="card" style="border-top:4px solid var(--${i[2] === 'ok' ? 'good' : i[2] === 'warn' ? 'warn' : 'crit'})"><div class="row between"><span style="width:28px;height:28px;color:var(--ink)">${I(i[0])}</span>${UI.pill(i[2] === 'ok' ? 'Ready' : i[2] === 'warn' ? 'Check' : 'Pending', i[2] === 'ok' ? 'good' : i[2] === 'warn' ? 'warn' : 'crit')}</div><div class="b ink mt" style="font-size:14px">${i[1]}</div><div class="small t2">${i[3]}</div></div>`).join('')}</div>
    <div class="grid g2">${UI.card('Exceptions', ex.map(e => chk(e[2], e[1], e[3])).join('<div class="mt"></div>') + `<div class="row mt">${UI.btn('Swap battery on ' + U.drones[U.drones.length - 1].name, { sm: 1, toast: 'Battery swap requested at the launch pad', done: 'Requested' })}${UI.btn('Request Operator Approval', { sm: 1, primary: 1, toast: 'Approval request sent to the pilot in command', done: 'Requested' })}</div>`, { icon: 'alert' })}
      ${UI.card('Pre-flight checklist', UI.steps(['Propellers, arms and landing gear inspected.', 'Payload lens clean, storage card empty.', 'Home point and emergency landing zones confirmed on site.', 'Observers in position and on the radio.', 'Launch area clear of people.']) + `<div class="row mt">${UI.btn('Summary & Launch', { primary: 1, go: 'plan/launch' })}</div>`)}</div>`; });

  /* ---------- Advanced · Summary & Launch ---------- */
  V.launch = view('launch', U => `<div class="grid g-2-1"><div class="col">
      ${UI.card(U.name, `<div class="mb">${U.objective}</div>${UI.facts([['mappin', 'Location', U.location], ['route', 'Route', `${U.pattern} · ${U.waypoints} waypoints`], ['drone', 'Drones', `${U.drones.length} (${U.drones.map(d => d.role.split(' · ')[0]).join(', ')})`], ['video', 'Payloads', [...new Set(U.drones.flatMap(d => [d.p1, d.p2]))].join(', ')], ['clock', 'Duration', `${U.minutes} min, launch ${launchAt(U)}`], ['grid', 'Coverage', `${U.coverage}% · GSD ${U.gsd} cm · ${VQ.fmt(U.images)} images`], ['db', 'Data', `~${U.dataGB} GB`], ['sun', 'Weather window', '09:00 – 11:10 AM']])}`, { icon: 'file', right: UI.pill(U.id, 'info') })}
      <div class="grid g2" style="margin:0">${UI.card('Risks', UI.list(U.risks.map(r => ({ icon: 'alert', tone: 'warn', title: r }))))}${UI.card('Mission rules', UI.steps(['Maximum altitude 120 m AGL; geofence buffer 20 m.', 'Land with 25% battery or more.', 'On link loss: continue 60 s, then return by the safe corridor.', `Alerts on: ${U.detect.join(', ')}.`]))}</div></div>
    <div class="col"><div class="card flush">${VQ.MMap.render({ uc: U.key, h: 260, labels: false, layers: { area: 1, path: 1, nfz: 1, drones: 0 } })}</div>
      ${UI.card('Readiness', chk('warn', '6 of 8 ready', 'Battery check on one drone and operator approval are open.') + `<div class="mt"><a data-go="plan/readiness">Open Mission Readiness ${I('chev')}</a></div>`)}</div></div>
    ${UI.card('Decision', `<div class="launch-row">${UI.btn('Approve Mission', { icon: 'checkc', toast: `${U.id} approved by ${D.user}`, done: 'Approved' })}${UI.btn('Schedule Mission', { icon: 'cal', toast: `${U.id} scheduled for 16 Sep, ${launchAt(U)}`, done: 'Scheduled' })}${UI.btn('Launch Mission', { primary: 1, icon: 'play', toast: `${U.id} launch sequence started. Opening Live Operations.`, done: 'Launching' })}<span class="t2" style="align-self:center">Launch stays locked until every readiness exception is cleared.</span></div>`, { cls: 'mb' })}`);
})();
